/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include "unistd.h"

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 141
#define YY_END_OF_BUFFER 142
static yyconst short int yy_accept[322] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   44,   44,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      142,  140,  137,  139,  139,   77,  117,   57,  140,  124,
       67,   68,   48,   46,   72,   47,   71,   49,   93,   93,
       69,   70,   54,   50,   53,   85,   87,   92,   65,   66,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   63,  140,   64,   88,   91,
       90,   89,  138,  138,   44,   45,   44,   38,   39,  141,
      119,  122,  123,  121,  141,  112,  111,  115,  141,  125,
      126,  127,  141,   81,   55,    0,    0,   62,   79,   60,

       73,   59,   74,   61,   86,   80,  104,   37,   43,   58,
        0,   93,  100,  109,   96,   94,   84,   52,   56,   51,
       82,   83,   92,    1,   92,   92,   92,    7,   92,   92,
       92,   92,   11,   12,   16,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   78,   44,
       38,   39,   41,   40,    0,   42,  121,  120,  118,  133,
      132,  134,  135,  130,  128,  131,  129,  136,  112,  115,
      114,  113,   76,   13,   17,  110,  104,  106,   99,  103,
      100,  109,  104,  109,   95,   96,    0,   75,    2,   92,
       92,   92,   92,   92,    9,   10,   92,   92,   92,   92,

       92,   92,   92,   92,   92,   92,   92,   92,   92,   29,
       92,   31,   32,   92,   92,  120,  136,  116,  114,    0,
       99,  101,  102,  104,  108,  107,   95,   97,   98,  105,
       92,   92,   92,   92,    8,   92,   92,   18,   92,   20,
       92,   92,   92,   92,   92,   92,   27,   92,   35,   92,
       33,   92,  136,  116,    0,  106,  102,  103,  107,    0,
       98,    0,  105,    0,    0,    3,    4,   92,   92,   36,
       92,   92,   92,   92,   92,   92,   92,   26,   28,   92,
       34,  136,  106,    0,    0,  105,   92,   92,   92,   92,
       19,   92,   92,   92,   23,   25,   92,  136,  105,    0,

       92,   92,   92,   92,   24,   21,   92,   92,   92,    6,
       92,   15,   92,   92,   92,   14,   22,   30,   92,    5,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   29,   29,   31,   29,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   33,   32,   32,
       34,   35,   36,    1,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   47,   48,   49,   32,   50,
       51,   52,   32,   53,   54,   55,   56,   57,   58,   59,
       60,   32,   61,   62,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    2,    3,    1,    4,    3,    1,    1,    1,
        1,    1,    5,    1,    1,    1,    1,    1,    6,    6,
        6,    1,    1,    1,    1,    1,    1,    1,    7,    7,
        7,    8,    8,    1,    1,    1,    9,    7,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
       10,    1,    1
    } ;

static yyconst short int yy_base[345] =
    {   0,
        0,    0,    3,    4,    7,    8,   69,   72,   74,   76,
       71,   78,   79,   86,   91,   96,  101,  103,    0,    0,
      678,  679,  679,  679,  679,   83,  671,  651,  666,  679,
      679,  679,  649,   87,  679,   93,  103,  121,  130,  137,
      651,  679,  647,  646,  645,   93,  679,    0,  679,  679,
      615,  615,   76,  616,  617,  114,   94,  609,   89,  124,
      622,  607,  128,  624,  616,  679,  598,  679,  679,  679,
      679,  679,  679,  679,    0,  679,    0,  656,  679,  113,
      679,  679,  679,  189,  247,    0,  679,  652,  596,  679,
      679,  679,  679,  679,  631,  105,  649,  679,  679,  679,

      679,  679,  679,  679,  679,  679,  239,  679,  679,  679,
      163,  246,  252,  271,  617,  290,  679,  679,  628,  679,
      679,  679,    0,  625,  609,  612,  599,    0,  594,  598,
      593,  595,    0,  589,    0,  594,  595,  599,  600,   94,
      600,  583,  585,  118,  208,  584,  225,  233,  679,    0,
      632,  679,  679,  679,  281,  679,    0,    0,  679,  679,
      679,  679,  679,  679,  679,  679,  679,    0,    0,  628,
        0,  679,  679,  679,  679,  679,  293,  297,  285,  300,
      312,  321,  324,  327,  591,  585,  166,  679,  679,  580,
      549,   88,  556,  531,    0,    0,  542,  534,  524,  503,

      438,  428,  429,  433,  425,  438,  424,  426,  434,    0,
      433,    0,    0,  424,  423,    0,    0,  447,    0,  336,
      346,  349,  352,  355,  358,  361,  407,  402,  401,  380,
      386,  371,  369,  375,    0,  374,  362,    0,  357,    0,
      358,  356,  351,  345,  337,  335,    0,  329,    0,  347,
        0,  342,    0,  357,  383,  386,  389,  393,  399,  408,
      325,  323,  412,  421,  427,    0,    0,  306,  304,    0,
      212,  298,  307,  283,  296,  289,  276,    0,    0,  276,
        0,    0,  431,  436,  439,  442,  267,  259,  263,  260,
        0,  254,  253,  238,    0,    0,  234,  679,  446,  450,

      229,  219,  216,  146,    0,    0,  136,  138,  120,    0,
      124,    0,  112,   63,   45,    0,    0,    0,   34,    0,
      679,  487,  497,  507,  517,  527,  537,  542,  551,  561,
      571,  581,  585,  590,  599,  600,  604,  606,  610,  614,
      618,  620,  624,  626
    } ;

static yyconst short int yy_def[345] =
    {   0,
      321,    1,    1,    1,    1,    1,    1,    1,  322,  322,
      323,  323,  324,  324,  325,  325,  326,  326,  327,  327,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  328,  321,  321,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  329,  321,  329,  330,  321,  331,
      321,  321,  321,  321,  321,  332,  321,  321,  333,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  334,  321,  321,  321,  321,  321,
      321,  321,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  321,  329,
      330,  321,  321,  321,  331,  321,  335,  336,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  337,  332,  321,
      338,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  339,  340,  321,  321,  321,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  336,  341,  321,  338,  321,
      321,  321,  321,  321,  321,  321,  339,  339,  342,  321,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  343,  321,  321,  321,  321,  321,  321,  321,
      342,  342,  321,  321,  321,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  344,  321,  321,  321,  321,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  321,  321,  321,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
        0,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321
    } ;

static yyconst short int yy_nxt[743] =
    {   0,
       22,   23,   24,   25,   26,   27,   22,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   48,
       48,   48,   48,   49,   22,   50,   48,   51,   52,   53,
       54,   55,   56,   48,   48,   57,   48,   48,   48,   58,
       59,   60,   61,   62,   63,   48,   64,   65,   48,   48,
       66,   67,   68,   69,   69,   70,   70,   71,   71,   72,
       72,   73,   74,   79,   73,   74,   76,   77,   76,   77,
       79,   82,   82,   80,   83,   84,  320,   94,   82,   82,
       80,   83,   84,   87,   87,  319,   88,   89,   87,   87,

      101,   88,   89,   91,   91,   91,   91,   95,  103,  121,
       92,  102,   92,   85,  122,  154,  318,  104,  105,  106,
       85,  107,  107,  107,  126,  155,  127,  137,   96,   22,
      156,   22,   22,  108,   22,   85,  133,   85,  109,  202,
      138,  233,  234,  134,  203,  110,  111,  135,  112,  112,
      112,  130,  317,  111,  174,  112,  112,  112,  175,  113,
      114,  139,  115,  207,  131,  316,  116,  114,  113,  132,
      208,  114,  144,  116,  315,  314,  140,  313,  114,  141,
      145,  107,  107,  107,  230,  230,  230,  146,  115,  157,
      157,  157,  157,  157,  312,  157,  157,  157,  157,  157,

      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  158,  158,  158,
      158,  158,  157,  157,  157,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  159,
      157,  157,  160,  161,  289,  311,  162,  177,  177,  177,
      310,  290,  111,  209,  112,  112,  112,  210,  309,  114,
      179,  179,  180,  212,  214,  178,  114,  213,  215,  308,
      114,  163,  116,  154,  182,  164,  182,  114,  181,  183,
      183,  183,  307,  155,  306,  305,  165,  304,  156,  166,

      303,  167,  168,  221,  221,  180,  187,  184,  112,  112,
      112,  177,  177,  177,  302,  177,  177,  177,  180,  180,
      180,  222,  301,  114,  297,  296,  116,  220,  295,  178,
      223,  223,  180,  178,  114,  294,  180,  293,  220,  183,
      183,  183,  224,  224,  224,  226,  226,  226,  181,  255,
      292,  255,  291,  288,  256,  256,  256,  184,  287,  262,
      225,  262,  254,  184,  221,  221,  180,  221,  221,  180,
      257,  257,  180,  224,  224,  224,  224,  224,  224,  259,
      259,  259,  222,  281,  280,  222,  279,  278,  258,  277,
      276,  225,  275,  274,  225,  273,  272,  260,  263,  263,

      263,  256,  256,  256,  283,  283,  283,  257,  257,  180,
      264,  257,  257,  180,  271,  270,  265,  259,  259,  259,
      269,  264,  284,  268,  267,  258,  259,  259,  259,  258,
      263,  263,  263,  266,  285,  260,  285,  262,  228,  286,
      286,  286,  264,  228,  260,  263,  263,  263,  265,  283,
      283,  283,  254,  264,  283,  283,  283,  286,  286,  286,
      299,  299,  299,  265,  299,  299,  299,  284,  299,  299,
      299,  252,  284,  251,  250,  249,  248,  247,  300,  246,
      245,  244,  300,  243,  242,  241,  300,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   78,   78,   78,

       78,   78,   78,   78,   78,   78,   78,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,  123,  123,  123,
      123,  150,  240,  150,  150,  150,  150,  150,  150,  150,
      150,  151,  151,  151,  151,  239,  151,  151,  151,  151,
      151,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  169,  238,  237,  236,  169,  169,  169,  169,  169,
      169,  171,  171,  171,  171,  185,  185,  235,  185,  157,

      157,  157,  232,  157,  157,  216,  216,  216,  216,  217,
      217,  219,  219,  219,  219,  227,  227,  231,  227,  229,
      229,  186,  229,  253,  253,  261,  261,  228,  261,  282,
      282,  298,  298,  218,  152,  211,  206,  205,  204,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  186,  176,  173,  172,  170,  152,  149,
      148,  147,  143,  142,  136,  129,  128,  125,  124,  120,
      119,  118,  117,  100,   99,   98,   97,  321,   21,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321
    } ;

static yyconst short int yy_chk[743] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    3,    4,    5,    6,    5,
        6,    7,    7,   11,    8,    8,    9,    9,   10,   10,
       12,   13,   13,   11,   13,   13,  319,   26,   14,   14,
       12,   14,   14,   15,   15,  315,   15,   15,   16,   16,

       34,   16,   16,   17,   17,   18,   18,   26,   36,   46,
       17,   34,   18,   13,   46,   80,  314,   36,   36,   37,
       14,   37,   37,   37,   53,   80,   53,   59,   26,    7,
       80,    7,    8,   38,    8,   17,   57,   18,   38,  140,
       59,  192,  192,   57,  140,   38,   39,   57,   39,   39,
       39,   56,  313,   40,   96,   40,   40,   40,   96,   39,
       39,   60,   39,  144,   56,  311,   39,   40,   39,   56,
      144,   39,   63,   40,  309,  308,   60,  307,   40,   60,
       63,  111,  111,  111,  187,  187,  187,   63,   39,   84,
       84,   84,   84,   84,  304,   84,   84,   84,   84,   84,

       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   85,   85,  271,  303,   85,  107,  107,  107,
      302,  271,  112,  145,  112,  112,  112,  145,  301,  107,
      113,  113,  113,  147,  148,  107,  112,  147,  148,  297,
      107,   85,  112,  155,  114,   85,  114,  112,  113,  114,
      114,  114,  294,  155,  293,  292,   85,  290,  155,   85,

      289,   85,   85,  179,  179,  179,  116,  114,  116,  116,
      116,  177,  177,  177,  288,  178,  178,  178,  180,  180,
      180,  179,  287,  177,  280,  277,  116,  178,  276,  177,
      181,  181,  181,  178,  177,  275,  180,  274,  178,  182,
      182,  182,  183,  183,  183,  184,  184,  184,  181,  220,
      273,  220,  272,  269,  220,  220,  220,  182,  268,  262,
      183,  261,  254,  184,  221,  221,  221,  222,  222,  222,
      223,  223,  223,  224,  224,  224,  225,  225,  225,  226,
      226,  226,  221,  252,  250,  222,  248,  246,  223,  245,
      244,  224,  243,  242,  225,  241,  239,  226,  230,  230,

      230,  255,  255,  255,  256,  256,  256,  257,  257,  257,
      230,  258,  258,  258,  237,  236,  230,  259,  259,  259,
      234,  230,  256,  233,  232,  257,  260,  260,  260,  258,
      263,  263,  263,  231,  264,  259,  264,  229,  228,  264,
      264,  264,  263,  227,  260,  265,  265,  265,  263,  283,
      283,  283,  218,  263,  284,  284,  284,  285,  285,  285,
      286,  286,  286,  265,  299,  299,  299,  283,  300,  300,
      300,  215,  284,  214,  211,  209,  208,  207,  286,  206,
      205,  204,  299,  203,  202,  201,  300,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  323,  323,  323,

      323,  323,  323,  323,  323,  323,  323,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  328,  328,  328,
      328,  329,  200,  329,  329,  329,  329,  329,  329,  329,
      329,  330,  330,  330,  330,  199,  330,  330,  330,  330,
      330,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  332,  198,  197,  194,  332,  332,  332,  332,  332,
      332,  333,  333,  333,  333,  334,  334,  193,  334,  335,

      335,  335,  191,  335,  335,  336,  336,  336,  336,  337,
      337,  338,  338,  338,  338,  339,  339,  190,  339,  340,
      340,  186,  340,  341,  341,  342,  342,  185,  342,  343,
      343,  344,  344,  170,  151,  146,  143,  142,  141,  139,
      138,  137,  136,  134,  132,  131,  130,  129,  127,  126,
      125,  124,  119,  115,   97,   95,   89,   88,   78,   67,
       65,   64,   62,   61,   58,   55,   54,   52,   51,   45,
       44,   43,   41,   33,   29,   28,   27,   21,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
    #include "parser_tab.h"
    #include "parsing_tree.h"
    #include "print_functions.h"
    extern int yyparse();
#define YY_NEVER_INTERACTIVE 1
#define YY_STACK_USED 1
#define INTERPOLATION 1

#define INBRACE 2

#define INBRACKET 3

#define END_OF_LINE_COMMENT 4

#define MULTILINE_COMMENT 5

#define STRING 6

#define MULTILINE_STRING 7

#define CHAR 8

#define OVER 9

#line 24 "lexer.l"
    #include <stdio.h>
    #include <string.h>
    #include "stringBuffer.h"
    #include "iohandler.h"
#line 31 "lexer.l"
    /*! Удалить символ из строки по его индексу в ней.
    * \param[in] str исходная строка.
    * \param[in] index индекс удаляемого символа.
    * \return 0, если удалено успешно, 1 - если нет.
    */
    int removeCharFromStringByIndex(char * str, int index); 

    /*! Удалить из строки нижние подчеркивания.
    * \param[in] str исходная строка.
    */
    void removeUnderline(char* str);

    /*! Опциональный вывод лексем в зависимости от значения флага.
    * \param[in] str выводимая строка.
    * \param[in] token выводимый токен.
    */
    void printHandler(char* str, char * token);

    int hasClosingBrace = 0;

    int hasPlus = 0;

    int hasOpenBracket = 0;

    int hasCloseBracket = 0;

    int needsTokens = 0;

    char tempIdent[1024];
    // Блок ключевых слов.
#line 702 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 63 "lexer.l"



    char bufferString[20480]; // Массив символов - буфер для строковых выражений.
    struct stringBuffer buff = {"", 0}; // Дополнительный буффер для строк.
    int line = 1;
    int multilineBegin;



    if(hasClosingBrace != 0)
    {
        hasClosingBrace = 0;
        return '}';
    }
    if(hasPlus != 0)
    {
        hasPlus = 0;
        return '+';
    }
    if(hasOpenBracket != 0)
    {
        hasOpenBracket = 0;
        return '(';
    }
    if(strlen(tempIdent) != 0)
    {
        char * t = (char*)malloc(strlen(tempIdent) + 1);
        strcpy(t, tempIdent);
        yylval.ident = t;
        tempIdent[0] = 0;
        return ID;
    }
    if(hasCloseBracket != 0)
    {
        hasCloseBracket = 0;
        hasPlus = 1;
        return ')';
    }


#line 891 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 322 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 679 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 104 "lexer.l"
{printHandler((char*)"AS_KEY_WORD", yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 105 "lexer.l"
{printHandler((char * )"AS?_KEY_WORD", yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 106 "lexer.l"
{printHandler((char*)"BREAK_KEY_WORD", yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 107 "lexer.l"
{
    printHandler((char*)"CLASS_KEY_WORD", yytext);
    return CLASS;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 111 "lexer.l"
{
    printHandler((char*)"CONSTRUCTOR_KEY_WORD", yytext);
    return CONSTRUCTOR;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 115 "lexer.l"
{printHandler((char*)"CONTINUE_KEY_WORD", yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 116 "lexer.l"
{
    printHandler((char*)"DO_KEY_WORD", yytext);
    return DO;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 120 "lexer.l"
{printHandler((char*)"ELSE_KEY_WORD", yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 121 "lexer.l"
{
    printHandler((char*)"FOR_KEY_WORD", yytext);
    return FOR;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 125 "lexer.l"
{
    printHandler((char*)"FUN_KEY_WORD", yytext);
    return FUNC;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 129 "lexer.l"
{printHandler((char*)"IF_KEY_WORD", yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 130 "lexer.l"
{
    printHandler((char*)"IN_KEY_WORD", yytext);
    return IN;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 134 "lexer.l"
{printHandler((char*)"!IN_KEY_WORD", yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 135 "lexer.l"
{printHandler((char*)"INTERFACE_KEY_WORD", yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 136 "lexer.l"
{
    printHandler((char*)"INTERNAL_KEY_WORD", yytext);
    return INTERNAL;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 140 "lexer.l"
{printHandler((char*)"IS_KEY_WORD", yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 141 "lexer.l"
{printHandler((char*)"!IS_KEY_WORD", yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 142 "lexer.l"
{printHandler((char*)"NULL_KEY_WORD", yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 143 "lexer.l"
{printHandler((char*)"OBJECT_KEY_WORD", yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 144 "lexer.l"
{
    printHandler((char*)"OPEN_KEY_WORD", yytext);
    return OPEN;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 148 "lexer.l"
{
    printHandler((char*)"PRIVATE_KEY_WORD", yytext);
    return PRIVATE;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 152 "lexer.l"
{
    printHandler((char*)"PROTECTED_KEY_WORD", yytext);
    return PROTECTED;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 156 "lexer.l"
{
    printHandler((char*)"PUBLIC_KEY_WORD", yytext);
    return PUBLIC;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 160 "lexer.l"
{printHandler((char*)"PACKAGE_KEY_WORD", yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 161 "lexer.l"
{printHandler((char*)"RETURN_KEY_WORD", yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 162 "lexer.l"
{
    printHandler((char*)"SUPER_KEY_WORD", yytext);
    return SUPER;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 166 "lexer.l"
{
    printHandler((char*)"THIS_KEY_WORD", yytext);
    return THIS;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 170 "lexer.l"
{printHandler((char*)"THROW_KEY_WORD", yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 171 "lexer.l"
{printHandler((char*)"TRY_KEY_WORD", yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 172 "lexer.l"
{printHandler((char*)"TYPEALIAS_KEY_WORD", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 173 "lexer.l"
{
    printHandler((char*)"VAL_KEY_WORD", yytext);
    return VAL;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 177 "lexer.l"
{
    printHandler((char*)"VAR_KEY_WORD", yytext);
    return VAR;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 181 "lexer.l"
{printHandler((char*)"WHEN_KEY_WORD", yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 182 "lexer.l"
{
    printHandler((char*)"WHILE_KEY_WORD", yytext);
    return WHILE;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 187 "lexer.l"
{
    printHandler((char*)"TRUE_KEY_WORD", yytext);
    return TRUE_LITERAL;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 191 "lexer.l"
{
    printHandler((char*)"FALSE_KEY_WORD", yytext);
    return FALSE_LITERAL;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 196 "lexer.l"
{bufferString[0] = 0; multilineBegin = line; yy_push_state(MULTILINE_COMMENT);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 197 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 198 "lexer.l"
{line += 1; strcat(bufferString, yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 199 "lexer.l"
{line += 1; strcat(bufferString, yytext);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 200 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 201 "lexer.l"
{printHandler((char*)"MULTILINE_COMMENT", bufferString); yy_pop_state();}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 202 "lexer.l"
{printf("ERROR: no closing */ in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 204 "lexer.l"
{bufferString[0] = 0; yy_push_state(END_OF_LINE_COMMENT);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 205 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 206 "lexer.l"
{printHandler((char*)"END_OF_LINE_COMMENT", bufferString);  line += 1; yy_pop_state();
return ENDL; }
	YY_BREAK
case YY_STATE_EOF(END_OF_LINE_COMMENT):
#line 208 "lexer.l"
{printHandler((char*)"END_OF_LINE_COMMENT", bufferString); BEGIN(INITIAL);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 210 "lexer.l"
{
    printHandler((char*)"PLUS_OPERATOR", yytext);
    return '+';
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 214 "lexer.l"
{
    printHandler((char*)"MINUS_OPERATOR", yytext);
    return '-';
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 218 "lexer.l"
{
    printHandler((char*)"MUL_OPERATOR", yytext);
    return '*';
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 222 "lexer.l"
{
    printHandler((char*)"DIV_OPERATOR", yytext);
    return '/';
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 226 "lexer.l"
{
    printHandler((char*)"ASSIGNMENT_OPERATOR", yytext);
    return '=';
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 230 "lexer.l"
{
    printHandler((char*)"GREATER_EQUAL_OPERATOR", yytext);
    return GREATER_EQUAL;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 234 "lexer.l"
{
    printHandler((char*)"LESS_EQUAL_OPERATOR", yytext);
    return LESS_EQUAL;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 238 "lexer.l"
{
    printHandler((char*)"GREATER_OPERATOR", yytext);
    return '>';
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 242 "lexer.l"
{
    printHandler((char*)"LESS_OPERATOR", yytext);
    return '<';
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 246 "lexer.l"
{
    printHandler((char*)"NOT_EQUAL_OPERATOR", yytext);
    return NOT_EQUAL;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 250 "lexer.l"
{
    printHandler((char*)"EQUAL_OPERATOR", yytext);
    return EQUAL;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 254 "lexer.l"
{
    printHandler((char*)"MOD_OPERATOR", yytext);
    return '%';
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 258 "lexer.l"
{
    printHandler((char*)"DIV_ASSIGNMENT_OPERATOR", yytext);
    return DIV_ASSIGNMENT;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 262 "lexer.l"
{
    printHandler((char*)"PLUS_ASSIGNMENT_OPERATOR", yytext);
    return PLUS_ASSIGNMENT;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 266 "lexer.l"
{
    printHandler((char*)"MUL_ASSIGNMENT_OPERATOR", yytext);
    return MUL_ASSIGNMENT;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 270 "lexer.l"
{
    printHandler((char*)"MINUS_ASSIGNMENT_OPERATOR", yytext);
    return MINUS_ASSIGNMENT;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 274 "lexer.l"
{
    printHandler((char*)"MOD_ASSIGNMENT_OPERATOR", yytext);
    return MOD_ASSIGNMENT;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 279 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    return '{';
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 283 "lexer.l"
{
    printHandler((char*)"RIGHT_BRACE", yytext);
    hasClosingBrace = 1;
    return ';';
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 288 "lexer.l"
{printHandler((char*)"LEFT_SQUARE_BRACKET", yytext);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 289 "lexer.l"
{printHandler((char*)"RIGHT_SQUARE_BRACKET", yytext);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 290 "lexer.l"
{
    printHandler((char*)"LEFT_ROUND_BRACKET", yytext);
    yy_push_state(INBRACKET);
    return '(';
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 295 "lexer.l"
{
    printHandler((char*)"RIGHT_ROUND_BRACKET", yytext);
    yy_pop_state();
    return ')';
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 300 "lexer.l"
{
    printHandler((char*)"COLON", yytext);
    return ':';
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 304 "lexer.l"
{
    printHandler((char*)"SEMICOLON", yytext);
    return ';';
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 308 "lexer.l"
{
    printHandler((char*)"DOT", yytext);
    return '.';
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 312 "lexer.l"
{
    printHandler((char*)"COMMA", yytext);
    return ',';
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 317 "lexer.l"
{
    printHandler((char*)"INCREMENT_OPERATOR", yytext);
    return INCREMENT;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 321 "lexer.l"
{
    printHandler((char*)"DECREMENT_OPERATOR", yytext);
    return DECREMENT;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 326 "lexer.l"
{printHandler((char*)"REF_EQUAL_OPERATOR", yytext);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 327 "lexer.l"
{printHandler((char*)"REF_NOT_EQUAL_OPERATOR", yytext);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 329 "lexer.l"
{
    printHandler((char*)"NOT_OPERATOR", yytext);
    return '!';
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 333 "lexer.l"
{
    printHandler((char*)"OR_OPERATOR", yytext);
    return DISJ;
} 
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 337 "lexer.l"
{
    printHandler((char*)"AND_OPERATOR", yytext);
    return CONJ;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 342 "lexer.l"
{
    printHandler((char*)"RANGE_OPERATOR", yytext);
    return RANGE;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 346 "lexer.l"
{printHandler((char*)"NOT_NULL_ASSERTION_OPERATOR", yytext);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 347 "lexer.l"
{printHandler((char*)"SAFE_CALL_OPERATOR", yytext);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 349 "lexer.l"
{printHandler((char*)"ELVIS_OPERATOR", yytext);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 350 "lexer.l"
{printHandler((char*)"UNIT_REFERENCE_OPERATOR", yytext);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 351 "lexer.l"
{printHandler((char*)"ALLOW_NULL_OPERATOR", yytext);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 352 "lexer.l"
{printHandler((char*)"LAMBDA_OPERATOR", yytext);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 353 "lexer.l"
{printHandler((char*)"ANNOTATION_OPERATOR", yytext);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 355 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    yy_push_state(INBRACE);
    return '{';
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 361 "lexer.l"
{
    printHandler((char*)"RIGHT_BRACE", yytext);
    hasClosingBrace = 1;
    yy_pop_state();
    return ';';
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 368 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    yy_push_state(INBRACE);
    return '{';
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 374 "lexer.l"
{
    printHandler((char*)"END_INTERPOLATION", yytext);
    bufferString[0] = 0;
    clearStringBuffer(&buff);
    hasPlus = 1;
    yy_pop_state();
    return ')';
}
	YY_BREAK
case YY_STATE_EOF(INBRACE):
#line 383 "lexer.l"
{
    printf("ERROR: expecting \"{\"\n");
    BEGIN(INITIAL);
    return -1;
}
	YY_BREAK
case YY_STATE_EOF(INTERPOLATION):
#line 389 "lexer.l"
{
    printf("ERROR: expecting \"{\"\n");
    BEGIN(INITIAL);
    return -1;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 395 "lexer.l"
{
    printHandler((char*)"IDENTIFIER", yytext);
    char * t = (char*)malloc(strlen(yytext) + 1);
    strcpy(t, yytext);
    yylval.ident = t;
    return ID;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 403 "lexer.l"
{ bufferString[0] = 0;
    strcat(bufferString, yytext);
    int buffLen = strlen(bufferString);
    if (bufferString[0] == '0' && buffLen > 1)
    {
        printf("ERROR: illegal using of zero in INT in line %d.\n", line);
        return -1;
    }
    else 
    {
        removeUnderline(bufferString);
        int res = atoi(bufferString);
        if(needsTokens) printf("(%d) - DECIMAL_INT\n", res);
        yylval.intLit = res;
        return INT_LITERAL;
    }
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 421 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 426 "lexer.l"
{ 
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    removeUnderline(bufferString);
    int result = strtol(bufferString + 2, NULL, 16);
    if(needsTokens) printf("(%d) - HEX_INT\n", result);
    yylval.intLit = result;
    return INT_LITERAL;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 436 "lexer.l"
{
    printf("ERROR: missing hex int value in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 441 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 446 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 451 "lexer.l"
{
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    removeUnderline(bufferString);
    int result = strtol(bufferString + 2, NULL, 2);
    if(needsTokens) printf("(%d) - BINARY_INT\n", result);
    yylval.intLit = result;
    return INT_LITERAL;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 461 "lexer.l"
{
    printf("ERROR: missing binary int value in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 466 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 471 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 476 "lexer.l"
{
    printf("ERROR: oot of range binary value in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 481 "lexer.l"
{
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    removeUnderline(bufferString);
    int resLen = strlen(bufferString);
    double result = atof(bufferString);
    if(needsTokens) printf("(%.*f) - DOUBLE\n", resLen, result);
    yylval.doubleLit = result;
    return DOUBLE_LITERAL;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 492 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 497 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 502 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 507 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 512 "lexer.l"
{
    printf("ERROR: the value is out of range in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 517 "lexer.l"
{
    bufferString[0] = 0;
    multilineBegin = line;
    printHandler((char*)"MULTILINE_STRING_BEGIN", yytext);
    yy_push_state(MULTILINE_STRING); 
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 523 "lexer.l"
{line += 1; strcat(bufferString, yytext);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 524 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 525 "lexer.l"
{
    printHandler((char*)"MULTILINE_STRING", bufferString);
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    strcpy(ns->buffer, bufferString);
    ns->length = strlen(bufferString);
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;
    printHandler((char*)"BEGIN_INTERPOLATION", yytext);
    bufferString[0] = 0;
    yy_push_state(INTERPOLATION);
    return STRING_LITERAL;
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 538 "lexer.l"
{
    printHandler((char*)"MULTILINE_STRING", bufferString);
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    strcpy(ns->buffer, bufferString);
    ns->length = strlen(bufferString);
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;
    strcpy(tempIdent, yytext + 1);
    hasCloseBracket = 1;
    printHandler((char*)"BEGIN_INTERPOLATION", (char*)"$");
    printHandler((char*)"IDENTIFIER", yytext + 1);
    printHandler((char*)"END_INTERPOLATION", (char*)" ");
    bufferString[0] = 0;
    return STRING_LITERAL;
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 554 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 555 "lexer.l"
{
    for (int i = 0; i < yyleng - 3; i++)
    {
        strcat(bufferString, "\"");        
    }
    printHandler((char*)"MULTILINE STRING", bufferString);
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    strcpy(ns->buffer, bufferString);
    ns->length = strlen(bufferString);
    yylval.stringLit = ns;
    printHandler((char*)"MULTILINE_STRING_END", (char*)"\"\"\"");
    yy_pop_state();
    return STRING_LITERAL;
}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_STRING):
#line 569 "lexer.l"
{printf("ERROR: no closing \"\"\" (three double-quotes) in MULTILINE STRING in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 571 "lexer.l"
{
    bufferString[0] = 0;
    multilineBegin = line;
    clearStringBuffer(&buff);
    printHandler((char*)"ESCAPED_STRING_BEGIN", yytext);
    yy_push_state(STRING);
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 578 "lexer.l"
{
    printHandler((char*)"ESCAPED_STRING", getSafeCString(&buff));

    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    memcpy(ns->buffer, buff.buffer, buff.length);
    ns->length = buff.length;
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;

    printHandler((char*)"BEGIN_INTERPOLATION", yytext);
    clearStringBuffer(&buff);
    yy_push_state(INTERPOLATION);
    return STRING_LITERAL;
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 593 "lexer.l"
{appendChar(&buff, yytext[0]);}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 594 "lexer.l"
{
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    memcpy(ns->buffer, buff.buffer, buff.length);
    ns->length = buff.length;
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;
    strcpy(tempIdent, yytext + 1);
    hasCloseBracket = 1;
    printHandler((char*)"ESCAPED_STRING", getSafeCString(&buff));
    printHandler((char*)"BEGIN_INTERPOLATION", (char*)"$");
    printHandler((char*)"IDENTIFIER", yytext + 1);
    printHandler((char*)"END_INTERPOLATION", (char*)" ");
    clearStringBuffer(&buff);
    bufferString[0] = 0;
    return STRING_LITERAL;
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 611 "lexer.l"
{appendChars(&buff, yytext);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 612 "lexer.l"
{printf("ERROR: no closing \" (double-quote) in STRING in line %d.\n", multilineBegin); line += 1; yy_pop_state(); return -1;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 613 "lexer.l"
{ 
    printHandler((char*)"ESCAPED STRING", getSafeCString(&buff)); 
    printHandler((char*)"ESCAPED_STRING_END", yytext);
    yy_pop_state();
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    memcpy(ns->buffer, buff.buffer, buff.length);
    ns->length = buff.length;
    yylval.stringLit = ns;
    return STRING_LITERAL;
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 623 "lexer.l"
{printf("ERROR: no closing \" (double-quote) in STRING in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 625 "lexer.l"
{bufferString[0] = 0; multilineBegin = line; clearStringBuffer(&buff); yy_push_state(CHAR);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 626 "lexer.l"
{appendChar(&buff, yytext[0]);}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 627 "lexer.l"
{printf("ERROR: no closing  \' (single-quote) in CHAR in line %d.\n", multilineBegin); line += 1; yy_pop_state(); return -1;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 628 "lexer.l"
{
    int buffLen = buff.length;
    int isOk = 0;
    if(buffLen > 1)
    {
        printf("ERROR: Too many characters in a character literal in line %d.\n", multilineBegin);
    }
    else if (buffLen <= 0)
    {
        printf("ERROR: empty character literal in line %d.\n", multilineBegin);
    }
    else
    {
        if (needsTokens) printf("(%c) - CHAR\n", buff.buffer[0]);
        isOk = 1;
    }
    yy_pop_state();
    if(isOk) 
    {        
        yylval.charLit = buff.buffer[0];
        return CHAR_LITERAL;
    }
    else
    {
        return -1;
    }
}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 655 "lexer.l"
{printf("ERROR: no closing \' (single-quote) in CHAR in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 657 "lexer.l"
{appendChar(&buff, '\n');}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 658 "lexer.l"
{appendChar(&buff, '\t');}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 659 "lexer.l"
{appendChar(&buff, '\b');}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 660 "lexer.l"
{appendChar(&buff, '\r');}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 661 "lexer.l"
{appendChar(&buff, '$');}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 662 "lexer.l"
{appendChar(&buff, '\"');}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 663 "lexer.l"
{appendChar(&buff, '\'');}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 664 "lexer.l"
{appendChar(&buff, '\\');}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 665 "lexer.l"
{
    if (strlen(yytext) < 4)
    {
        printf("ERROR: Illegal escape \'\\u\' in line %d\n", line);
        return -1;
    }
    int value = strtol(yytext+2,NULL, 16);
    if (value > 127)
    {
        printf("ERROR: non-supported UNICODE character in line %d.\n", line);
        return -1;
    }
    else
    {
        appendChar(&buff, value);
    }
}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 683 "lexer.l"
{
    // Игнорирование лишних пробелов и табуляций. 
}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 687 "lexer.l"
{
    line = line + 1;
}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 691 "lexer.l"
{
    line = line + 1;
    return ENDL;
}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 696 "lexer.l"
{
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    printf("%s - UNRECOGNIZED TOKEN.\n", bufferString);
    return -1;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 703 "lexer.l"
{ 
    BEGIN(OVER);
    return ';';
}
	YY_BREAK
case YY_STATE_EOF(OVER):
#line 708 "lexer.l"
{
    yyterminate();
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 712 "lexer.l"
ECHO;
	YY_BREAK
#line 2129 "lex.yy.c"
case YY_STATE_EOF(INBRACKET):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 322 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 322 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 321);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 712 "lexer.l"


int removeCharFromStringByIndex(char * str, int index) 
{
    int length = strlen(str); // Вычислить длину строки.
    if (index >= length || index < 0) // Удалить символ, если индекс выходит за границу строки. 
    {
        return 1;
    }
    for (int i = index; i < length; i++)
    str[i] = str[i + 1];

    return 0;
}

void removeUnderline(char* str)
{
    char* underline = strchr(str, '_');
    while (underline != NULL){
        underline = strchr(str, '_');
        int position = underline - str;
        removeCharFromStringByIndex(str, position);
    }
}

int main(int argc, char* argv[])
{
	if (argc < 2)
	{
		printf("The path to the input file is missing; use -h to get help using the utility.\n");
		return -1;
	}

    int needsDotCon = 0;
    int needsDotFile = 0;
	int needsHelp = 0;
    int opt = 0;

    while((opt = t_getopt(argc, argv, "cfht")) != -1)
    {
        switch(opt) 
        {
            case 'h':
                printf("%s", getHelp());
				needsHelp = 1;
                return 0;
                break;
            case 't':
                needsTokens = 1;
                break;
            case 'c':
                needsDotCon = 1;
                break;
            case 'f':
                needsDotFile = 1;
                break;
            case '?':
                printf("%c : unrecognized option; use -h to get help using the utility.\n", opt);
                return -1;
                break;
        }   
    }
	if (!needsHelp && argv[argc - 1][0] == '-')
	{
		printf("The path to the input file is missing; use -h to get help using the utility.\n");
		return -1;
	}

	yyin = fopen(argv[argc - 1], "r");

    printf("The parsing process has started.\n");

	yyparse();

    printf("The parsing process is completed.\n");

    if (needsDotCon || needsDotFile) 
    {   
        char * res = generateDotFromKotlinFile(root);
        if (needsDotFile)
        {
            FILE *f = fopen("result.gv", "w");
            fprintf(f, "%s", res);
            fclose(f);
        }
        if (needsDotCon)
        {
            printf("%s\n", res);
        }
    
    }

	return 0;
}

void printHandler(char* str, char * token)
{
    if(needsTokens != 0)
    {
        printf("(%s) - %s\n", token, str);
    }
}
