/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include "unistd.h"

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 167
#define YY_END_OF_BUFFER 168
static yyconst short int yy_accept[451] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   65,   65,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  168,  166,  162,  165,
      165,  100,  142,   79,  166,  149,   90,   91,   69,   67,
       95,   68,   94,   70,  118,  118,   92,   93,   76,   72,
       75,  108,  110,  117,   88,   89,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,   85,  166,   87,  111,  115,  114,  113,  163,  163,
       71,   86,  117,  117,  117,  117,  112,  116,   65,   66,
       65,   59,   60,  167,  144,  147,  148,  146,  167,  137,

      136,  140,  167,  150,  151,  152,  167,  164,  167,  167,
      167,  167,  167,  167,  104,   77,    0,    0,   84,  102,
       82,   96,   81,   97,   83,  109,  103,  129,   58,   64,
       80,    0,  118,  125,  134,  121,  119,  107,   74,   78,
       73,  105,  106,  117,   20,  117,  117,  117,   26,  117,
      117,  117,  117,  117,   30,   31,   35,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  101,  117,   31,  117,  117,  117,  117,   65,   59,
       60,   62,   61,    0,   63,  146,  145,  143,  158,  157,
      159,  160,  155,  153,  156,  154,  161,  137,  140,  139,

      138,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   99,   32,   36,  135,  129,  131,  124,  128,  125,
      134,  129,  134,  120,  121,    0,   98,   21,  117,  117,
      117,  117,  117,  117,   28,   29,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
       50,  117,   52,   53,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  145,  161,  141,  139,    0,    0,    0,
       15,    0,    0,    0,    0,    0,    0,   18,   19,    0,
      124,  126,  127,  129,  133,  132,  120,  122,  123,  130,
      117,  117,  117,  117,   27,  117,  117,  117,   37,  117,

       41,  117,  117,  117,  117,  117,  117,  117,   48,  117,
       56,  117,   54,  117,  117,  117,    5,  117,  117,  117,
      117,  161,  141,    0,    0,    0,    0,   12,    0,    0,
        0,    0,    0,  131,  127,  128,  132,    0,  123,    0,
      130,    0,    0,   22,   23,  117,  117,   57,   39,  117,
      117,  117,  117,  117,  117,  117,  117,   47,   49,  117,
       55,    7,  117,  117,  117,  117,  117,  161,   16,    0,
       13,    0,    0,    0,    0,    0,  131,    0,    0,  130,
      117,  117,  117,  117,   38,  117,  117,  117,  117,   44,
       46,  117,  117,  117,  117,  117,    1,  161,    0,    0,

        0,    0,    0,    8,  130,    0,  117,  117,  117,  117,
      117,   45,   42,  117,  117,  117,  117,    2,  117,    0,
        0,    0,   11,    0,  117,   25,  117,   34,   40,  117,
      117,    3,    6,  117,    0,    9,   14,    0,  117,   33,
       43,   51,    4,    0,   10,  117,    0,   24,   17,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   29,   29,   31,   29,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   33,   32,   32,
       34,   35,   36,    1,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   47,   48,   49,   32,   50,
       51,   52,   32,   53,   54,   55,   56,   57,   58,   59,
       60,   32,   61,   62,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    2,    3,    1,    4,    3,    1,    1,    1,
        1,    1,    5,    1,    1,    1,    1,    1,    6,    6,
        6,    1,    1,    1,    1,    1,    1,    1,    7,    7,
        7,    8,    8,    1,    1,    1,    9,    7,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
       10,    1,    1
    } ;

static yyconst short int yy_base[474] =
    {   0,
        0,    0,    3,    4,    7,    8,   69,   72,   49,   52,
       35,   39,   76,   80,   86,   90,  101,  113,  118,  134,
       91,  124,  139,  141,    0,    0,  829,  830,  830,  830,
      830,  104,  822,  802,  817,  830,  830,  830,  800,  132,
      830,  135,  135,   93,  182,  146,  802,  830,  798,  797,
      796,   75,  830,    0,  830,  830,  766,  766,   98,  767,
      768,  124,  154,  760,  119,  167,  773,  758,  165,  775,
      767,  830,  749,  830,  830,  830,  830,  830,  830,  830,
      785,  830,  171,  157,  177,  190,  830,  830,    0,  830,
        0,  806,  830,  227,  830,  830,  830,  246,  304,    0,

      830,  802,  746,  830,  830,  830,  830,  830,  123,  122,
      756,  112,  133,  767,  830,  779,  181,  797,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  296,  830,  830,
      830,  217,  303,  309,  328,  765,  347,  830,  830,  776,
      830,  830,  830,    0,  773,  757,  760,  747,    0,  742,
      746,  744,  740,  742,    0,  736,    0,  741,  742,  746,
      745,  746,  193,  746,  729,  731,  180,  265,  730,  282,
      290,  830,  731,  725,  737,  736,  267,  738,    0,  773,
      830,  830,  830,  338,  830,    0,    0,  830,  830,  830,
      830,  830,  830,  830,  830,  830,    0,    0,  769,    0,

      830,  736,  723,  722,  721,  715,  727,  726,  304,  728,
      309,  830,  830,  830,  830,  350,  354,  357,  369,  378,
      381,  384,  388,  729,  728,  391,  830,  830,  726,  709,
      140,  720,  707,  722,    0,    0,  717,  709,  715,  706,
      702,  706,  696,  697,  702,  694,  707,  694,  696,  704,
        0,  703,    0,    0,  694,  694,  704,  699,  690,  686,
      681,  682,  687,    0,    0,  729,    0,  680,  679,  694,
      830,  689,  680,  676,  671,  672,  677,  830,  830,  403,
      407,  410,  413,  416,  419,  422,  688,  687,  686,  441,
      674,  667,  665,  673,    0,  676,  668,  663,    0,  675,

        0,  661,  675,  674,  669,  664,  656,  655,    0,  649,
        0,  668,    0,  663,  655,  650,    0,  649,  663,  658,
      653,    0,  692,  643,  641,  646,  636,  830,  630,  641,
      622,  613,  444,  447,  450,  454,  460,  469,  609,  608,
      473,  482,  488,    0,    0,  591,  577,    0,    0,  269,
      559,  501,  502,  490,  503,  502,  491,    0,    0,  490,
        0,    0,  329,  492,  482,  496,  495,    0,  830,  480,
      830,  464,  459,  445,  459,  455,  492,  497,  500,  503,
      430,  429,  444,  439,    0,  435,  416,  415,  400,    0,
        0,  408,  414,  410,  407,  393,    0,  830,  390,  407,

      379,  374,  359,  830,  507,  511,  373,  353,  353,  337,
      341,    0,    0,  340,  342,  314,  319,    0,  311,  312,
      288,  284,  830,  210,  187,    0,  190,    0,    0,  173,
      152,    0,    0,  132,   98,  830,  830,   98,   80,    0,
        0,    0,    0,   72,  830,   61,   35,    0,  830,  830,
      548,  558,  568,  578,  588,  598,  603,  612,  622,  632,
      642,  646,  651,  660,  661,  665,  667,  671,  675,  679,
      681,  685,  687
    } ;

static yyconst short int yy_def[474] =
    {   0,
      450,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,  451,  451,  452,  452,  453,  453,  454,  454,
      455,  455,  456,  456,  456,  456,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  457,  450,  450,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  457,  457,  457,  457,  450,  450,  458,  450,
      458,  459,  450,  460,  450,  450,  450,  450,  450,  461,

      450,  450,  462,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  463,  450,  450,  450,  450,
      450,  450,  450,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  450,  457,  457,  457,  457,  457,  457,  458,  459,
      450,  450,  450,  460,  450,  464,  465,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  466,  461,  450,  467,

      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  468,  469,  450,  450,  450,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  465,  470,  450,  467,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  468,  468,  471,  450,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,

      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  472,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  471,  471,
      450,  450,  450,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  473,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  450,  450,  450,

      450,  450,  450,  450,  450,  450,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  450,
      450,  450,  450,  450,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  450,  450,  450,  450,  457,  457,
      457,  457,  457,  450,  450,  457,  450,  457,  450,    0,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450
    } ;

static yyconst short int yy_nxt[894] =
    {   0,
       28,   29,   30,   31,   32,   33,   28,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   54,
       54,   54,   54,   55,   28,   56,   54,   57,   58,   59,
       60,   61,   62,   54,   54,   63,   54,   54,   54,   64,
       65,   66,   67,   68,   69,   54,   70,   71,   54,   54,
       72,   73,   74,   75,   75,   76,   76,   77,   77,   78,
       78,   79,   80,   81,   79,   80,   81,   83,   90,   91,
       84,   83,   90,   91,   84,   85,   86,  449,   93,   85,
       86,  142,   93,  105,  105,   87,  143,   88,   94,   87,

      106,   88,   94,   96,   96,  129,   97,   98,  115,   82,
      130,   28,   82,  448,   28,   96,   96,  131,   97,   98,
      101,  101,  447,  102,  103,   99,  105,  105,  116,   28,
      446,   28,   28,  106,   28,   99,  101,  101,  445,  102,
      103,  108,  108,  108,  108,  122,  147,   99,  148,  117,
      124,  127,  444,  128,  128,  128,  123,  159,   99,  125,
      126,  151,  132,  207,  133,  133,  133,  204,  208,  152,
      160,  202,  443,  203,  153,  161,  135,  205,  109,  154,
      109,  110,  137,  110,  111,  209,  111,  135,  210,  112,
      113,  112,  113,  293,  294,  114,  155,  114,  132,  155,

      133,  133,  133,  156,  162,  442,  174,  157,  151,  167,
      157,  134,  135,  441,  136,  159,  173,  168,  137,  163,
      134,  153,  164,  135,  169,  248,  154,  162,  175,  183,
      213,  440,  249,  176,  214,  128,  128,  128,  243,  184,
      136,  439,  177,  244,  185,  178,  186,  186,  186,  186,
      186,  438,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  187,  187,  187,  187,  187,  186,
      186,  186,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,

      187,  187,  187,  187,  187,  187,  188,  186,  186,  189,
      190,  383,  261,  191,  216,  216,  216,  262,  384,  132,
      250,  133,  133,  133,  251,  437,  135,  218,  218,  219,
      253,  255,  217,  135,  254,  256,  436,  135,  192,  137,
      183,  221,  193,  221,  135,  220,  222,  222,  222,  275,
      184,  435,  434,  194,  276,  185,  195,  278,  196,  197,
      433,  279,  432,  226,  223,  133,  133,  133,  216,  216,
      216,  383,  216,  216,  216,  281,  281,  219,  393,  431,
      135,  430,  429,  137,  280,  428,  217,  219,  219,  219,
      217,  135,  427,  282,  426,  280,  283,  283,  219,  222,

      222,  222,  284,  284,  284,  219,  286,  286,  286,  290,
      290,  290,  425,  424,  220,  423,  333,  223,  333,  422,
      285,  334,  334,  334,  223,  281,  281,  219,  281,  281,
      219,  335,  335,  219,  284,  284,  284,  284,  284,  284,
      337,  337,  337,  282,  421,  420,  282,  419,  418,  336,
      417,  416,  285,  415,  414,  285,  413,  412,  338,  341,
      341,  341,  334,  334,  334,  377,  377,  377,  335,  335,
      219,  342,  335,  335,  219,  411,  410,  343,  337,  337,
      337,  409,  342,  378,  408,  407,  336,  337,  337,  337,
      336,  341,  341,  341,  404,  379,  338,  379,  403,  402,

      380,  380,  380,  342,  401,  338,  341,  341,  341,  343,
      377,  377,  377,  400,  342,  377,  377,  377,  380,  380,
      380,  405,  405,  405,  343,  405,  405,  405,  378,  405,
      405,  405,  399,  378,  397,  396,  395,  394,  392,  406,
      391,  390,  389,  406,  388,  387,  386,  406,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  107,  107,

      107,  107,  107,  107,  107,  107,  107,  107,  144,  144,
      144,  144,  179,  385,  179,  179,  179,  179,  179,  179,
      179,  179,  180,  180,  180,  180,  382,  180,  180,  180,
      180,  180,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  198,  381,  340,  340,  198,  198,  198,  198,
      198,  198,  200,  200,  200,  200,  224,  224,  376,  224,
      186,  186,  186,  375,  186,  186,  264,  264,  264,  264,
      265,  265,  267,  267,  267,  267,  287,  287,  374,  287,
      289,  289,  373,  289,  322,  322,  339,  339,  372,  339,
      368,  368,  398,  398,  371,  370,  369,  323,  367,  366,

      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  340,  288,  288,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  292,  291,  225,  288,  277,  274,  273,  272,
      271,  270,  269,  268,  266,  181,  263,  260,  259,  258,
      257,  252,  247,  246,  245,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,

      227,  225,  215,  212,  211,  206,  201,  199,  181,  140,
      172,  171,  170,  166,  165,  158,  150,  149,  146,  145,
      141,  140,  139,  138,  121,  120,  119,  118,  450,   27,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450

    } ;

static yyconst short int yy_chk[894] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    3,    4,    5,    6,    5,
        6,    7,    7,    9,    8,    8,   10,   11,   13,   13,
       11,   12,   14,   14,   12,   11,   11,  447,   15,   12,
       12,   52,   16,   21,   21,   11,   52,   11,   15,   12,

       21,   12,   16,   17,   17,   44,   17,   17,   32,    9,
       44,    9,   10,  446,   10,   18,   18,   44,   18,   18,
       19,   19,  444,   19,   19,   21,   22,   22,   32,    7,
      439,    7,    8,   22,    8,   17,   20,   20,  438,   20,
       20,   23,   23,   24,   24,   40,   59,   18,   59,   32,
       42,   43,  435,   43,   43,   43,   40,   65,   22,   42,
       42,   62,   46,  112,   46,   46,   46,  110,  112,   62,
       65,  109,  434,  109,   62,   65,   46,  110,   23,   62,
       24,   23,   46,   24,   23,  113,   24,   46,  113,   23,
       23,   24,   24,  231,  231,   23,   63,   24,   45,   84,

       45,   45,   45,   63,   66,  431,   84,   63,   83,   69,
       84,   45,   45,  430,   45,   85,   83,   69,   45,   66,
       45,   83,   66,   45,   69,  167,   83,   86,   85,   94,
      117,  427,  167,   85,  117,  132,  132,  132,  163,   94,
       45,  425,   86,  163,   94,   86,   98,   98,   98,   98,
       98,  424,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,

       98,   98,   98,   98,   98,   98,   98,   98,   98,   99,
       99,  350,  177,   99,  128,  128,  128,  177,  350,  133,
      168,  133,  133,  133,  168,  422,  128,  134,  134,  134,
      170,  171,  128,  133,  170,  171,  421,  128,   99,  133,
      184,  135,   99,  135,  133,  134,  135,  135,  135,  209,
      184,  420,  419,   99,  209,  184,   99,  211,   99,   99,
      417,  211,  416,  137,  135,  137,  137,  137,  216,  216,
      216,  363,  217,  217,  217,  218,  218,  218,  363,  415,
      216,  414,  411,  137,  217,  410,  216,  219,  219,  219,
      217,  216,  409,  218,  408,  217,  220,  220,  220,  221,

      221,  221,  222,  222,  222,  219,  223,  223,  223,  226,
      226,  226,  407,  403,  220,  402,  280,  221,  280,  401,
      222,  280,  280,  280,  223,  281,  281,  281,  282,  282,
      282,  283,  283,  283,  284,  284,  284,  285,  285,  285,
      286,  286,  286,  281,  400,  399,  282,  396,  395,  283,
      394,  393,  284,  392,  389,  285,  388,  387,  286,  290,
      290,  290,  333,  333,  333,  334,  334,  334,  335,  335,
      335,  290,  336,  336,  336,  386,  384,  290,  337,  337,
      337,  383,  290,  334,  382,  381,  335,  338,  338,  338,
      336,  341,  341,  341,  376,  342,  337,  342,  375,  374,

      342,  342,  342,  341,  373,  338,  343,  343,  343,  341,
      377,  377,  377,  372,  341,  378,  378,  378,  379,  379,
      379,  380,  380,  380,  343,  405,  405,  405,  377,  406,
      406,  406,  370,  378,  367,  366,  365,  364,  360,  380,
      357,  356,  355,  405,  354,  353,  352,  406,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  456,  456,

      456,  456,  456,  456,  456,  456,  456,  456,  457,  457,
      457,  457,  458,  351,  458,  458,  458,  458,  458,  458,
      458,  458,  459,  459,  459,  459,  347,  459,  459,  459,
      459,  459,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  461,  346,  340,  339,  461,  461,  461,  461,
      461,  461,  462,  462,  462,  462,  463,  463,  332,  463,
      464,  464,  464,  331,  464,  464,  465,  465,  465,  465,
      466,  466,  467,  467,  467,  467,  468,  468,  330,  468,
      469,  469,  329,  469,  470,  470,  471,  471,  327,  471,
      472,  472,  473,  473,  326,  325,  324,  323,  321,  320,

      319,  318,  316,  315,  314,  312,  310,  308,  307,  306,
      305,  304,  303,  302,  300,  298,  297,  296,  294,  293,
      292,  291,  289,  288,  287,  277,  276,  275,  274,  273,
      272,  270,  269,  268,  266,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  252,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  234,
      233,  232,  230,  229,  225,  224,  210,  208,  207,  206,
      205,  204,  203,  202,  199,  180,  178,  176,  175,  174,
      173,  169,  166,  165,  164,  162,  161,  160,  159,  158,
      156,  154,  153,  152,  151,  150,  148,  147,  146,  145,

      140,  136,  118,  116,  114,  111,  103,  102,   92,   81,
       73,   71,   70,   68,   67,   64,   61,   60,   58,   57,
       51,   50,   49,   47,   39,   35,   34,   33,   27,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
    #include "parser_tab.h"
    #include "parsing_tree.h"
    #include "print_functions.h"
    #include "modifier_head.h"
    extern int yyparse();
#define YY_NEVER_INTERACTIVE 1
#define YY_STACK_USED 1
#define INTERPOLATION 1

#define INBRACE 2

#define INBRACKET 3

#define FUNCTION 4

#define FUNC_BODY 5

#define END_OF_LINE_COMMENT 6

#define MULTILINE_COMMENT 7

#define STRING 8

#define MULTILINE_STRING 9

#define CHAR 10

#define MODIFIER 11

#define OVER 12

#line 28 "lexer.l"
    #include <stdio.h>
    #include <string.h>
    #include "stringBuffer.h"
    #include "iohandler.h"
#line 35 "lexer.l"
    /*! Удалить символ из строки по его индексу в ней.
    * \param[in] str исходная строка.
    * \param[in] index индекс удаляемого символа.
    * \return 0, если удалено успешно, 1 - если нет.
    */
    int removeCharFromStringByIndex(char * str, int index); 

    /*! Удалить из строки нижние подчеркивания.
    * \param[in] str исходная строка.
    */
    void removeUnderline(char* str);

    /*! Опциональный вывод лексем в зависимости от значения флага.
    * \param[in] str выводимая строка.
    * \param[in] token выводимый токен.
    */
    void printHandler(char* str, char * token);

    int hasClosingBrace = 0;

    int hasPlus = 0;

    int hasOpenBracket = 0;

    int hasCloseBracket = 0;

    int needsTokens = 0;

    char tempIdent[1024];

    struct ModifierHead head = {0,0,0,0,0,0,0};
    
    int line = 1;
    
    int multilineBegin;
#line 789 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 72 "lexer.l"



    char bufferString[20480]; // Массив символов - буфер для строковых выражений.
    struct stringBuffer buff = {"", 0}; // Дополнительный буффер для строк.



    if(hasClosingBrace != 0)
    {
        hasClosingBrace = 0;
        return '}';
    }
    if(hasPlus != 0)
    {
        hasPlus = 0;
        return '+';
    }
    if(hasOpenBracket != 0)
    {
        hasOpenBracket = 0;
        return '(';
    }
    if(strlen(tempIdent) != 0)
    {
        char * t = (char*)malloc(strlen(tempIdent) + 1);
        strcpy(t, tempIdent);
        yylval.ident = t;
        tempIdent[0] = 0;
        return ID;
    }
    if(hasCloseBracket != 0)
    {
        hasCloseBracket = 0;
        hasPlus = 1;
        return ')';
    }


#line 976 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 451 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 830 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 111 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 112 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 113 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 114 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 115 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 116 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 117 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 119 "lexer.l"
{
    if (head.isPublic == 0)
    {
        if((head.isInternal != 0) || (head.isProtected != 0) || (head.isPrivate != 0))
        {
            printf("ERROR: Incompatible visibility modifiers in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            printHandler((char*)"PUBLIC_KEY_WORD", yytext);
            head.isPublic = 1;
        }
    }
    else
    {
        printf("ERROR: Repeated \"public\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 141 "lexer.l"
{
    if (head.isInternal == 0)
    {
        if((head.isPublic != 0) || (head.isProtected != 0) || (head.isPrivate != 0))
        {
            printf("ERROR: Incompatible visibility modifiers in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            printHandler((char*)"INTERNAL_KEY_WORD", yytext);
            head.isInternal = 1;
        }
    }
    else
    {
        printf("ERROR: Repeated \"internal\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 163 "lexer.l"
{
    if (head.isProtected == 0)
    {
        if((head.isPublic != 0) || (head.isInternal != 0) || (head.isPrivate != 0))
        {
            printf("ERROR: Incompatible visibility modifiers in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            printHandler((char*)"PROTECTED_KEY_WORD", yytext);
            head.isProtected = 1;
        }
    }
    else
    {
        printf("ERROR: Repeated \"protected\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 185 "lexer.l"
{
    if (head.isPrivate == 0)
    {
        if((head.isPublic != 0) || (head.isInternal != 0) || (head.isProtected != 0))
        {
            printf("ERROR: Incompatible visibility modifiers in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            printHandler((char*)"PRIVATE_KEY_WORD", yytext);
            head.isPrivate = 1;
        }
    }
    else
    {
        printf("ERROR: Repeated \"private\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 207 "lexer.l"
{
    if (head.isOpen == 0)
    {
        if((head.isFinal != 0))
        {
            printf("ERROR: Incompatible modifiers \"open\" and \"final\" in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            printHandler((char*)"OPEN_KEY_WORD", yytext);
            head.isOpen = 1;
        }
    }
    else
    {
        printf("ERROR: Repeated \"open\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 229 "lexer.l"
{
    if (head.isFinal == 0)
    {
        if((head.isOpen != 0))
        {
            printf("ERROR: Incompatible modifiers \"open\" and \"final\" in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            head.isFinal = 1;
            printHandler((char*)"FINAL_KEY_WORD", yytext);
        }
    }
    else
    {
        printf("ERROR: Repeated \"final\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 251 "lexer.l"
{
    if (head.isOverride == 0)
    {
        printHandler((char*)"OVERRIDE_KEY_WORD", yytext);
        head.isOverride = 1;
    }
    else
    {
        printf("ERROR: Repeated \"override\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 265 "lexer.l"
{
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    clearModifierHead(&head);
    yy_pop_state();
    yy_push_state(FUNCTION);
    printHandler((char*)"FUN_KEY_WORD", yytext);
    return FUNC;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 274 "lexer.l"
{
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    clearModifierHead(&head);
    yy_pop_state();
    printHandler((char*)"CLASS_KEY_WORD", yytext);
    return CLASS;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 282 "lexer.l"
{
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    clearModifierHead(&head);
    yy_pop_state();
    printHandler((char*)"CONSTUCTOR_KEY_WORD", yytext);
    return CONSTRUCTOR;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 290 "lexer.l"
{
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    clearModifierHead(&head);
    yy_pop_state();
    printHandler((char*)"VAL_KEYWORD", yytext);
    return VAL;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 298 "lexer.l"
{
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    clearModifierHead(&head);
    yy_pop_state();
    printHandler((char*)"VAR_KEYWORD", yytext);
    return VAR;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 307 "lexer.l"
{printHandler((char*)"AS_KEY_WORD", yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 308 "lexer.l"
{printHandler((char * )"AS?_KEY_WORD", yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 309 "lexer.l"
{printHandler((char*)"BREAK_KEY_WORD", yytext);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 310 "lexer.l"
{
    printHandler((char*)"CLASS_KEY_WORD", yytext);
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    return CLASS;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 316 "lexer.l"
{
    printHandler((char*)"CONSTRUCTOR_KEY_WORD", yytext);
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    printHandler((char*)"CONSTUCTOR", yytext);
    return CONSTRUCTOR;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 323 "lexer.l"
{printHandler((char*)"CONTINUE_KEY_WORD", yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 324 "lexer.l"
{
    printHandler((char*)"DO_KEY_WORD", yytext);
    return DO;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 328 "lexer.l"
{printHandler((char*)"ELSE_KEY_WORD", yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 329 "lexer.l"
{
    printHandler((char*)"FOR_KEY_WORD", yytext);
    return FOR;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 333 "lexer.l"
{
    printHandler((char*)"FUN_KEY_WORD", yytext);
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    yy_push_state(FUNCTION);
    return FUNC;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 340 "lexer.l"
{printHandler((char*)"IF_KEY_WORD", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 341 "lexer.l"
{
    printHandler((char*)"IN_KEY_WORD", yytext);
    return IN;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 345 "lexer.l"
{printHandler((char*)"!IN_KEY_WORD", yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 346 "lexer.l"
{printHandler((char*)"INTERFACE_KEY_WORD", yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 347 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"INTERNAL_KEY_WORD", yytext);
    head.isInternal = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 353 "lexer.l"
{printHandler((char*)"IS_KEY_WORD", yytext);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 354 "lexer.l"
{printHandler((char*)"!IS_KEY_WORD", yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 355 "lexer.l"
{printHandler((char*)"NULL_KEY_WORD", yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 356 "lexer.l"
{printHandler((char*)"OBJECT_KEY_WORD", yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 357 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"FINAL_KEY_WORD", yytext);
    head.isFinal = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 363 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"OVERRIDE_KEY_WORD", yytext);
    head.isOverride = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 369 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"OPEN_KEY_WORD", yytext);
    head.isOpen = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 375 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"PRIVATE_KEY_WORD", yytext);
    head.isPrivate = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 381 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"PROTECTED_KEY_WORD", yytext);
    head.isProtected = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 387 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"PUBLIC_KEY_WORD", yytext);
    head.isPublic = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 393 "lexer.l"
{printHandler((char*)"PACKAGE_KEY_WORD", yytext);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 394 "lexer.l"
{printHandler((char*)"RETURN_KEY_WORD", yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 395 "lexer.l"
{
    printHandler((char*)"SUPER_KEY_WORD", yytext);
    return SUPER;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 399 "lexer.l"
{
    printHandler((char*)"THIS_KEY_WORD", yytext);
    return THIS;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 403 "lexer.l"
{printHandler((char*)"THROW_KEY_WORD", yytext);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 404 "lexer.l"
{printHandler((char*)"TRY_KEY_WORD", yytext);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 405 "lexer.l"
{printHandler((char*)"TYPEALIAS_KEY_WORD", yytext);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 406 "lexer.l"
{
    printHandler((char*)"VAL_KEY_WORD", yytext);
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    return VAL;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 412 "lexer.l"
{
    printHandler((char*)"VAR_KEY_WORD", yytext);
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    return VAR;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 418 "lexer.l"
{printHandler((char*)"WHEN_KEY_WORD", yytext);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 419 "lexer.l"
{
    printHandler((char*)"WHILE_KEY_WORD", yytext);
    return WHILE;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 424 "lexer.l"
{
    printHandler((char*)"TRUE_KEY_WORD", yytext);
    return TRUE_LITERAL;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 428 "lexer.l"
{
    printHandler((char*)"FALSE_KEY_WORD", yytext);
    return FALSE_LITERAL;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 433 "lexer.l"
{bufferString[0] = 0; multilineBegin = line; yy_push_state(MULTILINE_COMMENT);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 434 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 435 "lexer.l"
{line += 1; strcat(bufferString, yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 436 "lexer.l"
{line += 1; strcat(bufferString, yytext);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 437 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 438 "lexer.l"
{printHandler((char*)"MULTILINE_COMMENT", bufferString); yy_pop_state();}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 439 "lexer.l"
{printf("ERROR: no closing */ in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 441 "lexer.l"
{bufferString[0] = 0; yy_push_state(END_OF_LINE_COMMENT);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 442 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 443 "lexer.l"
{printHandler((char*)"END_OF_LINE_COMMENT", bufferString);  line += 1; yy_pop_state();
return ENDL; }
	YY_BREAK
case YY_STATE_EOF(END_OF_LINE_COMMENT):
#line 445 "lexer.l"
{printHandler((char*)"END_OF_LINE_COMMENT", bufferString); BEGIN(INITIAL);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 447 "lexer.l"
{
    printHandler((char*)"PLUS_OPERATOR", yytext);
    return '+';
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 451 "lexer.l"
{
    printHandler((char*)"MINUS_OPERATOR", yytext);
    return '-';
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 455 "lexer.l"
{
    printHandler((char*)"MUL_OPERATOR", yytext);
    return '*';
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 459 "lexer.l"
{
    printHandler((char*)"DIV_OPERATOR", yytext);
    return '/';
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 463 "lexer.l"
{
    printHandler((char*)"ASSIGNMENT_OPERATOR", yytext);
    yy_pop_state();
    return '=';
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 468 "lexer.l"
{
    printHandler((char*)"ASSIGNMENT_OPERATOR", yytext);
    return '=';
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 472 "lexer.l"
{
    printHandler((char*)"GREATER_EQUAL_OPERATOR", yytext);
    return GREATER_EQUAL;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 476 "lexer.l"
{
    printHandler((char*)"LESS_EQUAL_OPERATOR", yytext);
    return LESS_EQUAL;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 480 "lexer.l"
{
    printHandler((char*)"GREATER_OPERATOR", yytext);
    return '>';
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 484 "lexer.l"
{
    printHandler((char*)"LESS_OPERATOR", yytext);
    return '<';
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 488 "lexer.l"
{
    printHandler((char*)"NOT_EQUAL_OPERATOR", yytext);
    return NOT_EQUAL;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 492 "lexer.l"
{
    printHandler((char*)"EQUAL_OPERATOR", yytext);
    return EQUAL;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 496 "lexer.l"
{
    printHandler((char*)"MOD_OPERATOR", yytext);
    return '%';
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 500 "lexer.l"
{
    printHandler((char*)"DIV_ASSIGNMENT_OPERATOR", yytext);
    return DIV_ASSIGNMENT;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 504 "lexer.l"
{
    printHandler((char*)"PLUS_ASSIGNMENT_OPERATOR", yytext);
    return PLUS_ASSIGNMENT;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 508 "lexer.l"
{
    printHandler((char*)"MUL_ASSIGNMENT_OPERATOR", yytext);
    return MUL_ASSIGNMENT;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 512 "lexer.l"
{
    printHandler((char*)"MINUS_ASSIGNMENT_OPERATOR", yytext);
    return MINUS_ASSIGNMENT;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 516 "lexer.l"
{
    printHandler((char*)"MOD_ASSIGNMENT_OPERATOR", yytext);
    return MOD_ASSIGNMENT;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 521 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    return '{';
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 525 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    yy_push_state(FUNC_BODY);
    return '{';
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 530 "lexer.l"
{
    printHandler((char*)"RIGHT_BRACE", yytext);
    hasClosingBrace = 1;
    return ';';
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 535 "lexer.l"
{printHandler((char*)"LEFT_SQUARE_BRACKET", yytext);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 536 "lexer.l"
{printHandler((char*)"RIGHT_SQUARE_BRACKET", yytext);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 537 "lexer.l"
{
    printHandler((char*)"LEFT_ROUND_BRACKET", yytext);
    yy_push_state(INBRACKET);
    return '(';
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 542 "lexer.l"
{
    printHandler((char*)"RIGHT_ROUND_BRACKET", yytext);
    yy_pop_state();
    return ')';
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 547 "lexer.l"
{
    printHandler((char*)"COLON", yytext);
    return ':';
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 551 "lexer.l"
{
    printHandler((char*)"SEMICOLON", yytext);
    return ';';
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 555 "lexer.l"
{
    printHandler((char*)"DOT", yytext);
    return '.';
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 559 "lexer.l"
{
    printHandler((char*)"COMMA", yytext);
    return ',';
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 564 "lexer.l"
{
    printHandler((char*)"INCREMENT_OPERATOR", yytext);
    return INCREMENT;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 568 "lexer.l"
{
    printHandler((char*)"DECREMENT_OPERATOR", yytext);
    return DECREMENT;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 573 "lexer.l"
{printHandler((char*)"REF_EQUAL_OPERATOR", yytext);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 574 "lexer.l"
{printHandler((char*)"REF_NOT_EQUAL_OPERATOR", yytext);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 576 "lexer.l"
{
    printHandler((char*)"NOT_OPERATOR", yytext);
    return '!';
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 580 "lexer.l"
{
    printHandler((char*)"OR_OPERATOR", yytext);
    return DISJ;
} 
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 584 "lexer.l"
{
    printHandler((char*)"AND_OPERATOR", yytext);
    return CONJ;
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 589 "lexer.l"
{
    printHandler((char*)"RANGE_OPERATOR", yytext);
    return RANGE;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 593 "lexer.l"
{printHandler((char*)"NOT_NULL_ASSERTION_OPERATOR", yytext);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 594 "lexer.l"
{printHandler((char*)"SAFE_CALL_OPERATOR", yytext);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 596 "lexer.l"
{printHandler((char*)"ELVIS_OPERATOR", yytext);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 597 "lexer.l"
{printHandler((char*)"UNIT_REFERENCE_OPERATOR", yytext);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 598 "lexer.l"
{printHandler((char*)"ALLOW_NULL_OPERATOR", yytext);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 599 "lexer.l"
{printHandler((char*)"LAMBDA_OPERATOR", yytext);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 600 "lexer.l"
{printHandler((char*)"ANNOTATION_OPERATOR", yytext);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 602 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    yy_push_state(INBRACE);
    return '{';
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 608 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    yy_push_state(INBRACE);
    return '{';
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 614 "lexer.l"
{
    printHandler((char*)"RIGHT_BRACE", yytext);
    hasClosingBrace = 1;
    yy_pop_state();
    return ';';
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 621 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    yy_push_state(INBRACE);
    return '{';
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 627 "lexer.l"
{
    printHandler((char*)"END_INTERPOLATION", yytext);
    bufferString[0] = 0;
    clearStringBuffer(&buff);
    hasPlus = 1;
    yy_pop_state();
    return ')';
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 636 "lexer.l"
{
    printHandler((char*)"RIGHT_BRACE", yytext);
    hasClosingBrace = 1;
    yy_pop_state();
    if (YYSTATE == FUNCTION)
    {
        yy_pop_state();
    }
    return ';';
}
	YY_BREAK
case YY_STATE_EOF(INBRACE):
#line 647 "lexer.l"
{
    printf("ERROR: expecting \"}\".\n");
    BEGIN(INITIAL);
    return -1;
}
	YY_BREAK
case YY_STATE_EOF(INTERPOLATION):
#line 653 "lexer.l"
{
    printf("ERROR: expecting \"}\".\n");
    BEGIN(INITIAL);
    return -1;
}
	YY_BREAK
case YY_STATE_EOF(FUNC_BODY):
#line 659 "lexer.l"
{
    printf("ERROR: expecting \"}\".\n");
    BEGIN(INITIAL);
    return -1;
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 665 "lexer.l"
{
    printHandler((char*)"IDENTIFIER", yytext);
    char * t = (char*)malloc(strlen(yytext) + 1);
    strcpy(t, yytext);
    yylval.ident = t;
    return ID;
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 673 "lexer.l"
{ bufferString[0] = 0;
    strcat(bufferString, yytext);
    int buffLen = strlen(bufferString);
    if (bufferString[0] == '0' && buffLen > 1)
    {
        printf("ERROR: illegal using of zero in INT in line %d.\n", line);
        return -1;
    }
    else 
    {
        removeUnderline(bufferString);
        int res = atoi(bufferString);
        if(needsTokens) printf("(%d) - DECIMAL_INT\n", res);
        yylval.intLit = res;
        return INT_LITERAL;
    }
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 691 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 696 "lexer.l"
{ 
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    removeUnderline(bufferString);
    int result = strtol(bufferString + 2, NULL, 16);
    if(needsTokens) printf("(%d) - HEX_INT\n", result);
    yylval.intLit = result;
    return INT_LITERAL;
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 706 "lexer.l"
{
    printf("ERROR: missing hex int value in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 711 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 716 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 721 "lexer.l"
{
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    removeUnderline(bufferString);
    int result = strtol(bufferString + 2, NULL, 2);
    if(needsTokens) printf("(%d) - BINARY_INT\n", result);
    yylval.intLit = result;
    return INT_LITERAL;
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 731 "lexer.l"
{
    printf("ERROR: missing binary int value in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 736 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 741 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 746 "lexer.l"
{
    printf("ERROR: oot of range binary value in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 751 "lexer.l"
{
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    removeUnderline(bufferString);
    int resLen = strlen(bufferString);
    double result = atof(bufferString);
    if(needsTokens) printf("(%.*f) - DOUBLE\n", resLen, result);
    yylval.doubleLit = result;
    return DOUBLE_LITERAL;
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 762 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 767 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 772 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 777 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 782 "lexer.l"
{
    printf("ERROR: the value is out of range in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 787 "lexer.l"
{
    bufferString[0] = 0;
    multilineBegin = line;
    printHandler((char*)"MULTILINE_STRING_BEGIN", yytext);
    yy_push_state(MULTILINE_STRING); 
}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 793 "lexer.l"
{line += 1; strcat(bufferString, yytext);}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 794 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 795 "lexer.l"
{
    printHandler((char*)"MULTILINE_STRING", bufferString);
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    strcpy(ns->buffer, bufferString);
    ns->length = strlen(bufferString);
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;
    printHandler((char*)"BEGIN_INTERPOLATION", yytext);
    bufferString[0] = 0;
    yy_push_state(INTERPOLATION);
    return STRING_LITERAL;
}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 808 "lexer.l"
{
    printHandler((char*)"MULTILINE_STRING", bufferString);
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    strcpy(ns->buffer, bufferString);
    ns->length = strlen(bufferString);
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;
    strcpy(tempIdent, yytext + 1);
    hasCloseBracket = 1;
    printHandler((char*)"BEGIN_INTERPOLATION", (char*)"$");
    printHandler((char*)"IDENTIFIER", yytext + 1);
    printHandler((char*)"END_INTERPOLATION", (char*)" ");
    bufferString[0] = 0;
    return STRING_LITERAL;
}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 824 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 825 "lexer.l"
{
    for (int i = 0; i < yyleng - 3; i++)
    {
        strcat(bufferString, "\"");        
    }
    printHandler((char*)"MULTILINE STRING", bufferString);
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    strcpy(ns->buffer, bufferString);
    ns->length = strlen(bufferString);
    yylval.stringLit = ns;
    printHandler((char*)"MULTILINE_STRING_END", (char*)"\"\"\"");
    yy_pop_state();
    return STRING_LITERAL;
}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_STRING):
#line 839 "lexer.l"
{printf("ERROR: no closing \"\"\" (three double-quotes) in MULTILINE STRING in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 841 "lexer.l"
{
    bufferString[0] = 0;
    multilineBegin = line;
    clearStringBuffer(&buff);
    printHandler((char*)"ESCAPED_STRING_BEGIN", yytext);
    yy_push_state(STRING);
}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 848 "lexer.l"
{
    printHandler((char*)"ESCAPED_STRING", getSafeCString(&buff));

    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    memcpy(ns->buffer, buff.buffer, buff.length);
    ns->length = buff.length;
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;

    printHandler((char*)"BEGIN_INTERPOLATION", yytext);
    clearStringBuffer(&buff);
    yy_push_state(INTERPOLATION);
    return STRING_LITERAL;
}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 863 "lexer.l"
{appendChar(&buff, yytext[0]);}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 864 "lexer.l"
{
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    memcpy(ns->buffer, buff.buffer, buff.length);
    ns->length = buff.length;
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;
    strcpy(tempIdent, yytext + 1);
    hasCloseBracket = 1;
    printHandler((char*)"ESCAPED_STRING", getSafeCString(&buff));
    printHandler((char*)"BEGIN_INTERPOLATION", (char*)"$");
    printHandler((char*)"IDENTIFIER", yytext + 1);
    printHandler((char*)"END_INTERPOLATION", (char*)" ");
    clearStringBuffer(&buff);
    bufferString[0] = 0;
    return STRING_LITERAL;
}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 881 "lexer.l"
{appendChars(&buff, yytext);}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 882 "lexer.l"
{printf("ERROR: no closing \" (double-quote) in STRING in line %d.\n", multilineBegin); line += 1; yy_pop_state(); return -1;}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 883 "lexer.l"
{ 
    printHandler((char*)"ESCAPED STRING", getSafeCString(&buff)); 
    printHandler((char*)"ESCAPED_STRING_END", yytext);
    yy_pop_state();
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    memcpy(ns->buffer, buff.buffer, buff.length);
    ns->length = buff.length;
    yylval.stringLit = ns;
    return STRING_LITERAL;
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 893 "lexer.l"
{printf("ERROR: no closing \" (double-quote) in STRING in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 895 "lexer.l"
{bufferString[0] = 0; multilineBegin = line; clearStringBuffer(&buff); yy_push_state(CHAR);}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 896 "lexer.l"
{appendChar(&buff, yytext[0]);}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 897 "lexer.l"
{printf("ERROR: no closing  \' (single-quote) in CHAR in line %d.\n", multilineBegin); line += 1; yy_pop_state(); return -1;}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 898 "lexer.l"
{
    int buffLen = buff.length;
    int isOk = 0;
    if(buffLen > 1)
    {
        printf("ERROR: Too many characters in a character literal in line %d.\n", multilineBegin);
    }
    else if (buffLen <= 0)
    {
        printf("ERROR: empty character literal in line %d.\n", multilineBegin);
    }
    else
    {
        if (needsTokens) printf("(%c) - CHAR\n", buff.buffer[0]);
        isOk = 1;
    }
    yy_pop_state();
    if(isOk) 
    {        
        yylval.charLit = buff.buffer[0];
        return CHAR_LITERAL;
    }
    else
    {
        return -1;
    }
}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 925 "lexer.l"
{printf("ERROR: no closing \' (single-quote) in CHAR in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 927 "lexer.l"
{appendChar(&buff, '\n');}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 928 "lexer.l"
{appendChar(&buff, '\t');}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 929 "lexer.l"
{appendChar(&buff, '\b');}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 930 "lexer.l"
{appendChar(&buff, '\r');}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 931 "lexer.l"
{appendChar(&buff, '$');}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 932 "lexer.l"
{appendChar(&buff, '\"');}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 933 "lexer.l"
{appendChar(&buff, '\'');}
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 934 "lexer.l"
{appendChar(&buff, '\\');}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 935 "lexer.l"
{
    if (strlen(yytext) < 4)
    {
        printf("ERROR: Illegal escape \'\\u\' in line %d\n", line);
        return -1;
    }
    int value = strtol(yytext+2,NULL, 16);
    if (value > 127)
    {
        printf("ERROR: non-supported UNICODE character in line %d.\n", line);
        return -1;
    }
    else
    {
        appendChar(&buff, value);
    }
}
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 953 "lexer.l"
{
    // Игнорирование лишних пробелов и табуляций. 
}
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 957 "lexer.l"
{
    line = line + 1;
}
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 961 "lexer.l"
{
    line = line + 1;
}
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 965 "lexer.l"
{
    line = line + 1;
    return ENDL;
}
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 970 "lexer.l"
{
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    printf("%s - UNRECOGNIZED TOKEN.\n", bufferString);
    return -1;
}
	YY_BREAK
case YY_STATE_EOF(MODIFIER):
#line 977 "lexer.l"
{
    BEGIN(OVER);
    printf("ERROR: Exprecting top level declaration in line %d.\n", multilineBegin);
    return -1;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 983 "lexer.l"
{ 
    BEGIN(OVER);
    return ';';
}
	YY_BREAK
case YY_STATE_EOF(OVER):
#line 988 "lexer.l"
{
    yyterminate();
}
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 992 "lexer.l"
ECHO;
	YY_BREAK
#line 2589 "lex.yy.c"
case YY_STATE_EOF(INBRACKET):
case YY_STATE_EOF(FUNCTION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 451 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 451 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 450);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 992 "lexer.l"


int removeCharFromStringByIndex(char * str, int index) 
{
    int length = strlen(str); // Вычислить длину строки.
    if (index >= length || index < 0) // Удалить символ, если индекс выходит за границу строки. 
    {
        return 1;
    }
    for (int i = index; i < length; i++)
    str[i] = str[i + 1];

    return 0;
}

void removeUnderline(char* str)
{
    char* underline = strchr(str, '_');
    while (underline != NULL){
        underline = strchr(str, '_');
        int position = underline - str;
        removeCharFromStringByIndex(str, position);
    }
}

int main(int argc, char* argv[])
{
	if (argc < 2)
	{
		printf("The path to the input file is missing; use -h to get help using the utility.\n");
		return -1;
	}

    int needsDotCon = 0;
    int needsDotFile = 0;
	int needsHelp = 0;
    int opt = 0;

    while((opt = t_getopt(argc, argv, "cfht")) != -1)
    {
        switch(opt) 
        {
            case 'h':
                printf("%s", getHelp());
				needsHelp = 1;
                return 0;
                break;
            case 't':
                needsTokens = 1;
                break;
            case 'c':
                needsDotCon = 1;
                break;
            case 'f':
                needsDotFile = 1;
                break;
            case '?':
                printf("%c : unrecognized option; use -h to get help using the utility.\n", opt);
                return -1;
                break;
        }   
    }
	if (!needsHelp && argv[argc - 1][0] == '-')
	{
		printf("The path to the input file is missing; use -h to get help using the utility.\n");
		return -1;
	}

	yyin = fopen(argv[argc - 1], "r");

    printf("The parsing process has started.\n");

	yyparse();

    printf("The parsing process is completed.\n");

    if (needsDotCon || needsDotFile) 
    {   
        char * res = generateDotFromKotlinFile(root);
        if (needsDotFile)
        {
            FILE *f = fopen("result.gv", "w");
            fprintf(f, "%s", res);
            fclose(f);
        }
        if (needsDotCon)
        {
            printf("%s\n", res);
        }
    
    }

	return 0;
}

void printHandler(char* str, char * token)
{
    if(needsTokens != 0)
    {
        printf("(%s) - %s\n", token, str);
    }
}
