/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 168
#define YY_END_OF_BUFFER 169
static yyconst short int yy_accept[456] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   66,   66,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  169,  167,  163,  166,
      166,  101,  143,   80,  167,  150,   91,   92,   70,   68,
       96,   69,   95,   71,  119,  119,   93,   94,   77,   73,
       76,  109,  111,  118,  118,   89,   90,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,   86,  167,   88,  112,  116,  115,  114,  164,
      164,   72,   87,  118,  118,  118,  118,  113,  117,   66,
       67,   66,   60,   61,  168,  145,  148,  149,  147,  168,

      138,  137,  141,  168,  151,  152,  153,  168,  165,  168,
      168,  168,  168,  168,  168,  105,   78,    0,    0,   85,
      103,   83,   97,   82,   98,   84,  110,  104,  130,   59,
       65,   81,    0,  119,  126,  135,  122,  120,  108,   75,
       79,   74,  106,  107,  118,  118,   20,  118,  118,  118,
       27,  118,  118,  118,  118,  118,   31,   32,   36,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  102,  118,   32,  118,  118,  118,  118,
       66,   60,   61,   63,   62,    0,   64,  147,  146,  144,
      159,  158,  160,  161,  156,  154,  157,  155,  162,  138,

      141,  140,  139,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  100,   33,   37,  136,  130,  132,  125,
      129,  126,  135,  130,  135,  121,  122,    0,   99,  118,
       21,  118,  118,  118,  118,  118,  118,   29,   30,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,   51,  118,   53,   54,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  146,  162,  142,  140,
        0,    0,    0,   15,    0,    0,    0,    0,    0,    0,
       18,   19,    0,  125,  127,  128,  130,  134,  133,  121,
      123,  124,  131,  118,  118,  118,  118,  118,   28,  118,

      118,  118,   38,  118,   42,  118,  118,  118,  118,  118,
      118,  118,   49,  118,   57,  118,   55,  118,  118,  118,
        5,  118,  118,  118,  118,  162,  142,    0,    0,    0,
        0,   12,    0,    0,    0,    0,    0,  132,  128,  129,
      133,    0,  124,    0,  131,    0,    0,   22,   23,   24,
      118,  118,   58,   40,  118,  118,  118,  118,  118,  118,
      118,  118,   48,   50,  118,   56,    7,  118,  118,  118,
      118,  118,  162,   16,    0,   13,    0,    0,    0,    0,
        0,  132,    0,    0,  131,  118,  118,  118,  118,   39,
      118,  118,  118,  118,   45,   47,  118,  118,  118,  118,

      118,    1,  162,    0,    0,    0,    0,    0,    8,  131,
        0,  118,  118,  118,  118,  118,   46,   43,  118,  118,
      118,  118,    2,  118,    0,    0,    0,   11,    0,  118,
       26,  118,   35,   41,  118,  118,    3,    6,  118,    0,
        9,   14,    0,  118,   34,   44,   52,    4,    0,   10,
      118,    0,   25,   17,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   31,   32,   31,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   34,   33,   33,
       35,   36,   37,    1,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   48,   49,   50,   33,   51,
       52,   53,   33,   54,   55,   56,   57,   58,   59,   60,
       61,   33,   62,   63,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    3,    1,    4,    3,    1,    1,    1,
        1,    1,    5,    1,    1,    1,    1,    1,    6,    6,
        6,    1,    1,    1,    1,    1,    1,    1,    7,    7,
        7,    7,    8,    8,    1,    1,    1,    9,    7,    7,
        7,    7,    7,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,   10,    1,    1
    } ;

static yyconst short int yy_base[479] =
    {   0,
        0,    0,    3,    4,    7,    8,   70,   73,   50,   53,
       35,   39,   77,   81,   87,   91,  102,  115,  120,  136,
       92,  126,  141,  143,    0,    0,  835,  836,  836,  836,
      836,  106,  828,  808,  823,  836,  836,  836,  806,  127,
      836,  132,  144,  141,  185,  154,  808,  836,  804,  803,
      802,   76,  836,  772,    0,  836,  836,  770,  770,  117,
      771,  772,  161,  105,  764,   67,  170,  777,  762,  122,
      779,  771,  836,  753,  836,  836,  836,  836,  836,  836,
      836,  790,  836,  164,  126,  180,  175,  836,  836,    0,
      836,    0,  811,  836,  223,  836,  836,  836,  245,  304,

        0,  836,  807,  750,  836,  836,  836,  836,  836,  128,
      132,  760,   97,   56,  771,  836,  784,  179,  802,  836,
      836,  836,  836,  836,  836,  836,  836,  836,  296,  836,
      836,  836,  223,  303,  310,  331,  769,  345,  836,  836,
      781,  836,  836,  836,    0,  751,  777,  760,  763,  750,
        0,  745,  749,  747,  743,  745,    0,  739,    0,  744,
      745,  749,  748,  749,  160,  749,  732,  734,  144,  174,
      733,  271,  289,  836,  734,  728,  740,  739,  266,  741,
        0,  777,  836,  836,  836,  324,  836,    0,    0,  836,
      836,  836,  836,  836,  836,  836,  836,  836,    0,    0,

      773,    0,  836,  739,  726,  725,  724,  718,  730,  729,
      286,  731,  299,  836,  836,  836,  836,  352,  355,  358,
      361,  381,  384,  387,  390,  732,  731,  393,  836,  729,
      836,  728,  711,  184,  722,  709,  724,    0,    0,  719,
      711,  717,  708,  704,  708,  698,  699,  704,  696,  709,
      696,  698,  706,    0,  705,    0,    0,  696,  696,  706,
      701,  692,  688,  683,  684,  689,    0,    0,  732,    0,
      682,  681,  696,  836,  691,  682,  678,  673,  674,  679,
      836,  836,  410,  396,  416,  419,  422,  425,  428,  690,
      689,  688,  432,  664,  675,  668,  666,  674,    0,  677,

      669,  664,    0,  676,    0,  662,  676,  675,  670,  665,
      657,  656,    0,  650,    0,  664,    0,  654,  643,  624,
        0,  619,  621,  616,  611,    0,  635,  573,  505,  510,
      505,  836,  504,  518,  513,  508,  448,  452,  457,  460,
      463,  466,  516,  515,  473,  493,  498,    0,    0,    0,
      498,  499,    0,    0,  268,  493,  500,  501,  485,  499,
      497,  486,    0,    0,  485,    0,    0,  312,  468,  454,
      467,  465,    0,  836,  449,  836,  451,  453,  443,  456,
      455,  501,  504,  507,  510,  434,  432,  449,  435,    0,
      423,  419,  418,  403,    0,    0,  411,  417,  413,  407,

      377,    0,  836,  375,  388,  381,  378,  364,  836,  513,
      524,  377,  354,  353,  342,  348,    0,    0,  346,  349,
      336,  342,    0,  327,  327,  317,  316,  836,  314,  298,
        0,  300,    0,    0,  284,  196,    0,    0,  195,  166,
      836,  836,  168,  120,    0,    0,    0,    0,   81,  836,
       62,   35,    0,  836,  836,  562,  572,  582,  592,  602,
      612,  617,  626,  636,  646,  656,  660,  665,  674,  675,
      679,  681,  685,  689,  693,  695,  699,  701
    } ;

static yyconst short int yy_def[479] =
    {   0,
      455,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,  456,  456,  457,  457,  458,  458,  459,  459,
      460,  460,  461,  461,  461,  461,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  462,  462,  455,  455,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  462,  462,  462,  462,  455,  455,  463,
      455,  463,  464,  455,  465,  455,  455,  455,  455,  455,

      466,  455,  455,  467,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  468,  455,  455,  455,
      455,  455,  455,  455,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  455,  462,  462,  462,  462,  462,  462,
      463,  464,  455,  455,  455,  465,  455,  469,  470,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  471,  466,

      455,  472,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  473,  474,  455,  455,  462,
      455,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  470,  475,  455,  472,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  473,
      473,  476,  455,  462,  462,  462,  462,  462,  462,  462,

      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  477,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  476,  476,  455,  455,  455,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  478,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  462,

      462,  462,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  462,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  462,  462,  462,  455,  455,  455,  455,  455,  462,
      462,  462,  462,  462,  462,  462,  462,  462,  462,  455,
      455,  455,  455,  462,  462,  462,  462,  462,  455,  455,
      462,  455,  462,  455,    0,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455
    } ;

static yyconst short int yy_nxt[901] =
    {   0,
       28,   29,   30,   31,   32,   33,   28,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       55,   55,   55,   55,   56,   28,   57,   55,   58,   59,
       60,   61,   62,   63,   55,   55,   64,   55,   55,   55,
       65,   66,   67,   68,   69,   70,   55,   71,   72,   55,
       55,   73,   74,   75,   76,   76,   77,   77,   78,   78,
       79,   79,   80,   81,   82,   80,   81,   82,   84,   91,
       92,   85,   84,   91,   92,   85,   86,   87,  454,   94,
       86,   87,  143,   94,  106,  106,   88,  144,   89,   95,

       88,  107,   89,   95,   97,   97,  161,   98,   99,  211,
      116,   83,  212,   28,   83,  453,   28,   97,   97,  162,
       98,   99,  102,  102,  163,  103,  104,  100,  106,  106,
      117,   28,  452,   28,   28,  107,   28,  100,  102,  102,
      123,  103,  104,  109,  109,  109,  109,  125,  157,  209,
      100,  124,  118,  130,  210,  158,  126,  127,  131,  159,
      128,  100,  129,  129,  129,  132,  149,  169,  150,  157,
      133,  451,  134,  134,  134,  170,  176,  204,  206,  205,
      159,  110,  171,  110,  111,  136,  111,  112,  207,  112,
      251,  138,  113,  114,  113,  114,  136,  252,  115,  153,

      115,  133,  153,  134,  134,  134,  246,  154,  164,  450,
      175,  247,  155,  164,  135,  155,  136,  156,  137,  161,
      156,  449,  138,  165,  135,  185,  166,  136,  179,  215,
      253,  180,  177,  216,  254,  186,  448,  178,  297,  298,
      187,  129,  129,  129,  137,  188,  188,  188,  188,  188,
      447,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  189,  189,  189,  189,  189,  189,  188,
      188,  188,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  190,  188,  188,  191,
      192,  388,  264,  193,  218,  218,  218,  265,  389,  133,
      256,  134,  134,  134,  257,  446,  185,  136,  220,  220,
      221,  258,  278,  219,  136,  259,  186,  279,  136,  194,
      138,  187,  445,  195,  223,  136,  223,  222,  281,  224,
      224,  224,  282,  444,  196,  388,  443,  197,  442,  198,
      199,  228,  398,  134,  134,  134,  441,  440,  225,  439,
      218,  218,  218,  218,  218,  218,  284,  284,  221,  221,
      221,  221,  138,  136,  438,  437,  283,  436,  435,  219,
      434,  433,  219,  432,  136,  285,  431,  283,  221,  286,

      286,  221,  224,  224,  224,  287,  287,  287,  289,  289,
      289,  293,  293,  293,  284,  284,  221,  430,  222,  429,
      428,  225,  427,  337,  288,  337,  426,  225,  338,  338,
      338,  425,  424,  285,  284,  284,  221,  339,  339,  221,
      287,  287,  287,  287,  287,  287,  341,  341,  341,  423,
      345,  345,  345,  285,  422,  421,  340,  420,  419,  288,
      418,  417,  288,  346,  416,  342,  338,  338,  338,  347,
      382,  382,  382,  415,  346,  339,  339,  221,  339,  339,
      221,  341,  341,  341,  341,  341,  341,  414,  413,  383,
      412,  345,  345,  345,  340,  409,  408,  340,  407,  406,

      342,  405,  404,  342,  346,  402,  384,  401,  384,  400,
      347,  385,  385,  385,  399,  346,  345,  345,  345,  382,
      382,  382,  382,  382,  382,  385,  385,  385,  410,  410,
      410,  410,  410,  410,  397,  347,  396,  395,  383,  394,
      393,  383,  410,  410,  410,  392,  391,  411,  390,  387,
      411,  386,  344,  344,  381,  380,  379,  378,  377,  376,
      375,  411,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,  101,  101,  101,  101,  101,  101,  101,  101,

      101,  101,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  145,  145,  145,  145,  181,  374,  181,  181,
      181,  181,  181,  181,  181,  181,  182,  182,  182,  182,
      327,  182,  182,  182,  182,  182,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  200,  372,  371,  370,
      200,  200,  200,  200,  200,  200,  202,  202,  202,  202,
      226,  226,  369,  226,  188,  188,  188,  368,  188,  188,
      267,  267,  267,  267,  268,  268,  270,  270,  270,  270,
      290,  290,  367,  290,  292,  292,  366,  292,  326,  326,

      343,  343,  365,  343,  373,  373,  403,  403,  364,  363,
      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  344,  291,  291,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  296,  295,  294,  227,  291,
      280,  277,  276,  275,  274,  273,  272,  271,  269,  183,
      266,  263,  262,  261,  260,  255,  250,  249,  248,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,

      234,  233,  232,  231,  230,  229,  227,  217,  214,  213,
      208,  203,  201,  183,  141,  174,  173,  172,  168,  167,
      160,  152,  151,  148,  147,  146,  142,  141,  140,  139,
      122,  121,  120,  119,  455,   27,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455

    } ;

static yyconst short int yy_chk[901] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,    5,    6,
        5,    6,    7,    7,    9,    8,    8,   10,   11,   13,
       13,   11,   12,   14,   14,   12,   11,   11,  452,   15,
       12,   12,   52,   16,   21,   21,   11,   52,   11,   15,

       12,   21,   12,   16,   17,   17,   66,   17,   17,  114,
       32,    9,  114,    9,   10,  451,   10,   18,   18,   66,
       18,   18,   19,   19,   66,   19,   19,   21,   22,   22,
       32,    7,  449,    7,    8,   22,    8,   17,   20,   20,
       40,   20,   20,   23,   23,   24,   24,   42,   64,  113,
       18,   40,   32,   44,  113,   64,   42,   42,   44,   64,
       43,   22,   43,   43,   43,   44,   60,   70,   60,   85,
       46,  444,   46,   46,   46,   70,   85,  110,  111,  110,
       85,   23,   70,   24,   23,   46,   24,   23,  111,   24,
      169,   46,   23,   23,   24,   24,   46,  169,   23,   63,

       24,   45,   84,   45,   45,   45,  165,   63,   67,  443,
       84,  165,   63,   87,   45,   84,   45,   63,   45,   86,
       84,  440,   45,   67,   45,   95,   67,   45,   87,  118,
      170,   87,   86,  118,  170,   95,  439,   86,  234,  234,
       95,  133,  133,  133,   45,   99,   99,   99,   99,   99,
      436,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,

       99,   99,   99,   99,   99,   99,   99,   99,   99,  100,
      100,  355,  179,  100,  129,  129,  129,  179,  355,  134,
      172,  134,  134,  134,  172,  435,  186,  129,  135,  135,
      135,  173,  211,  129,  134,  173,  186,  211,  129,  100,
      134,  186,  432,  100,  136,  134,  136,  135,  213,  136,
      136,  136,  213,  430,  100,  368,  429,  100,  427,  100,
      100,  138,  368,  138,  138,  138,  426,  425,  136,  424,
      218,  218,  218,  219,  219,  219,  220,  220,  220,  221,
      221,  221,  138,  218,  422,  421,  219,  420,  419,  218,
      416,  415,  219,  414,  218,  220,  413,  219,  221,  222,

      222,  222,  223,  223,  223,  224,  224,  224,  225,  225,
      225,  228,  228,  228,  284,  284,  284,  412,  222,  408,
      407,  223,  406,  283,  224,  283,  405,  225,  283,  283,
      283,  404,  401,  284,  285,  285,  285,  286,  286,  286,
      287,  287,  287,  288,  288,  288,  289,  289,  289,  400,
      293,  293,  293,  285,  399,  398,  286,  397,  394,  287,
      393,  392,  288,  293,  391,  289,  337,  337,  337,  293,
      338,  338,  338,  389,  293,  339,  339,  339,  340,  340,
      340,  341,  341,  341,  342,  342,  342,  388,  387,  338,
      386,  345,  345,  345,  339,  381,  380,  340,  379,  378,

      341,  377,  375,  342,  345,  372,  346,  371,  346,  370,
      345,  346,  346,  346,  369,  345,  347,  347,  347,  382,
      382,  382,  383,  383,  383,  384,  384,  384,  385,  385,
      385,  410,  410,  410,  365,  347,  362,  361,  382,  360,
      359,  383,  411,  411,  411,  358,  357,  385,  356,  352,
      410,  351,  344,  343,  336,  335,  334,  333,  331,  330,
      329,  411,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  458,  458,  458,  458,  458,  458,  458,  458,
      458,  458,  459,  459,  459,  459,  459,  459,  459,  459,

      459,  459,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  462,  462,  462,  462,  463,  328,  463,  463,
      463,  463,  463,  463,  463,  463,  464,  464,  464,  464,
      327,  464,  464,  464,  464,  464,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  466,  325,  324,  323,
      466,  466,  466,  466,  466,  466,  467,  467,  467,  467,
      468,  468,  322,  468,  469,  469,  469,  320,  469,  469,
      470,  470,  470,  470,  471,  471,  472,  472,  472,  472,
      473,  473,  319,  473,  474,  474,  318,  474,  475,  475,

      476,  476,  316,  476,  477,  477,  478,  478,  314,  312,
      311,  310,  309,  308,  307,  306,  304,  302,  301,  300,
      298,  297,  296,  295,  294,  292,  291,  290,  280,  279,
      278,  277,  276,  275,  273,  272,  271,  269,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  255,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  240,  237,  236,  235,  233,  232,  230,  227,  226,
      212,  210,  209,  208,  207,  206,  205,  204,  201,  182,
      180,  178,  177,  176,  175,  171,  168,  167,  166,  164,
      163,  162,  161,  160,  158,  156,  155,  154,  153,  152,

      150,  149,  148,  147,  146,  141,  137,  119,  117,  115,
      112,  104,  103,   93,   82,   74,   72,   71,   69,   68,
       65,   62,   61,   59,   58,   54,   51,   50,   49,   47,
       39,   35,   34,   33,   27,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
    #include "parser_tab.h"
    #include "parsing_tree.h"
    #include "print_functions.h"
    #include "modifier_head.h"
    extern int yyparse();
#define YY_NEVER_INTERACTIVE 1
#define YY_STACK_USED 1
#define INTERPOLATION 1

#define INBRACE 2

#define INBRACKET 3

#define FUNCTION 4

#define FUNC_BODY 5

#define END_OF_LINE_COMMENT 6

#define MULTILINE_COMMENT 7

#define STRING 8

#define MULTILINE_STRING 9

#define CHAR 10

#define MODIFIER 11

#define OVER 12

#line 28 "lexer.l"
    #include <stdio.h>
    #include <string.h>
    #include "stringBuffer.h"
    #include "iohandler.h"
#line 35 "lexer.l"
    /*! Удалить символ из строки по его индексу в ней.
    * \param[in] str исходная строка.
    * \param[in] index индекс удаляемого символа.
    * \return 0, если удалено успешно, 1 - если нет.
    */
    int removeCharFromStringByIndex(char * str, int index); 

    /*! Удалить из строки нижние подчеркивания.
    * \param[in] str исходная строка.
    */
    void removeUnderline(char* str);

    /*! Опциональный вывод лексем в зависимости от значения флага.
    * \param[in] str выводимая строка.
    * \param[in] token выводимый токен.
    */
    void printHandler(char* str, char * token);

    int hasClosingBrace = 0;

    int hasPlus = 0;

    int hasOpenBracket = 0;

    int hasCloseBracket = 0;

    char tempIdent[1024];

    struct ModifierHead head = {0,0,0,0,0,0,0};
    
    int line = 1;
    
    int multilineBegin;
#line 788 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 70 "lexer.l"



    char bufferString[20480]; // Массив символов - буфер для строковых выражений.
    struct stringBuffer buff = {"", 0}; // Дополнительный буффер для строк.



    if(hasClosingBrace != 0)
    {
        hasClosingBrace = 0;
        return '}';
    }
    if(hasPlus != 0)
    {
        hasPlus = 0;
        return '+';
    }
    if(hasOpenBracket != 0)
    {
        hasOpenBracket = 0;
        return '(';
    }
    if(strlen(tempIdent) != 0)
    {
        char * t = (char*)malloc(strlen(tempIdent) + 1);
        strcpy(t, tempIdent);
        yylval.ident = t;
        tempIdent[0] = 0;
        return ID;
    }
    if(hasCloseBracket != 0)
    {
        hasCloseBracket = 0;
        hasPlus = 1;
        return ')';
    }


#line 975 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 456 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 836 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 109 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 110 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 111 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 112 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 113 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 114 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 115 "lexer.l"
{printf("ERROR: Modifiers is incompatible with local variables.\n"); return -1;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 117 "lexer.l"
{
    if (head.isPublic == 0)
    {
        if((head.isInternal != 0) || (head.isProtected != 0) || (head.isPrivate != 0))
        {
            printf("ERROR: Incompatible visibility modifiers in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            printHandler((char*)"PUBLIC_KEY_WORD", yytext);
            head.isPublic = 1;
        }
    }
    else
    {
        printf("ERROR: Repeated \"public\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 139 "lexer.l"
{
    if (head.isInternal == 0)
    {
        if((head.isPublic != 0) || (head.isProtected != 0) || (head.isPrivate != 0))
        {
            printf("ERROR: Incompatible visibility modifiers in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            printHandler((char*)"INTERNAL_KEY_WORD", yytext);
            head.isInternal = 1;
        }
    }
    else
    {
        printf("ERROR: Repeated \"internal\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 161 "lexer.l"
{
    if (head.isProtected == 0)
    {
        if((head.isPublic != 0) || (head.isInternal != 0) || (head.isPrivate != 0))
        {
            printf("ERROR: Incompatible visibility modifiers in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            printHandler((char*)"PROTECTED_KEY_WORD", yytext);
            head.isProtected = 1;
        }
    }
    else
    {
        printf("ERROR: Repeated \"protected\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 183 "lexer.l"
{
    if (head.isPrivate == 0)
    {
        if((head.isPublic != 0) || (head.isInternal != 0) || (head.isProtected != 0))
        {
            printf("ERROR: Incompatible visibility modifiers in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            printHandler((char*)"PRIVATE_KEY_WORD", yytext);
            head.isPrivate = 1;
        }
    }
    else
    {
        printf("ERROR: Repeated \"private\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 205 "lexer.l"
{
    if (head.isOpen == 0)
    {
        if((head.isFinal != 0))
        {
            printf("ERROR: Incompatible modifiers \"open\" and \"final\" in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            printHandler((char*)"OPEN_KEY_WORD", yytext);
            head.isOpen = 1;
        }
    }
    else
    {
        printf("ERROR: Repeated \"open\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 227 "lexer.l"
{
    if (head.isFinal == 0)
    {
        if((head.isOpen != 0))
        {
            printf("ERROR: Incompatible modifiers \"open\" and \"final\" in line %d.\n", line);
            BEGIN(INITIAL);
            return -1;    
        }
        else
        {
            head.isFinal = 1;
            printHandler((char*)"FINAL_KEY_WORD", yytext);
        }
    }
    else
    {
        printf("ERROR: Repeated \"final\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 249 "lexer.l"
{
    if (head.isOverride == 0)
    {
        printHandler((char*)"OVERRIDE_KEY_WORD", yytext);
        head.isOverride = 1;
    }
    else
    {
        printf("ERROR: Repeated \"override\" modifier in line %d.\n", line);
        BEGIN(INITIAL);
        return -1;
    }
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 263 "lexer.l"
{
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    clearModifierHead(&head);
    yy_pop_state();
    yy_push_state(FUNCTION);
    printHandler((char*)"FUN_KEY_WORD", yytext);
    return FUNC;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 272 "lexer.l"
{
    printf("ERROR: Class Unsupported in this  version.\n");
    BEGIN(INITIAL);
    return -1;
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    clearModifierHead(&head);
    yy_pop_state();
    printHandler((char*)"CLASS_KEY_WORD", yytext);
    return CLASS;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 283 "lexer.l"
{
    printf("ERROR: Constructor Unsupported in this  version.\n");
    BEGIN(INITIAL);
    return -1;
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    clearModifierHead(&head);
    yy_pop_state();
    printHandler((char*)"CONSTUCTOR_KEY_WORD", yytext);
    return CONSTRUCTOR;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 294 "lexer.l"
{
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    clearModifierHead(&head);
    yy_pop_state();
    printHandler((char*)"VAL_KEYWORD", yytext);
    return VAL;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 302 "lexer.l"
{
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    clearModifierHead(&head);
    yy_pop_state();
    printHandler((char*)"VAR_KEYWORD", yytext);
    return VAR;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 311 "lexer.l"
{
    printf("ERROR: AS Unsupported in this  version.\n", line);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"AS_KEY_WORD", yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 317 "lexer.l"
{
    printf("ERROR: AS? Unsupported in this  version.\n", line);
    BEGIN(INITIAL);
    return -1;
    printHandler((char * )"AS?_KEY_WORD", yytext);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 323 "lexer.l"
{
    printHandler((char * )"ARRAY_KEY_WORD", yytext);
    return ARRAY;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 327 "lexer.l"
{
    printf("ERROR: Break Unsupported in this  version.\n", line);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"BREAK_KEY_WORD", yytext);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 333 "lexer.l"
{
    printf("ERROR: Class Unsupported in this  version.\n", line);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"CLASS_KEY_WORD", yytext);
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    return CLASS;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 342 "lexer.l"
{
    printf("ERROR: Constructor Unsupported in this  version.\n", line);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"CONSTRUCTOR_KEY_WORD", yytext);
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    return CONSTRUCTOR;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 351 "lexer.l"
{
    printf("ERROR: Continue Unsupported in this  version.\n", line);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"CONTINUE_KEY_WORD", yytext);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 357 "lexer.l"
{
    printHandler((char*)"DO_KEY_WORD", yytext);
    return DO;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 361 "lexer.l"
{printHandler((char*)"ELSE_KEY_WORD", yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 362 "lexer.l"
{
    printHandler((char*)"FOR_KEY_WORD", yytext);
    return FOR;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 366 "lexer.l"
{
    printHandler((char*)"FUN_KEY_WORD", yytext);
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    yy_push_state(FUNCTION);
    return FUNC;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 373 "lexer.l"
{printHandler((char*)"IF_KEY_WORD", yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 374 "lexer.l"
{
    printHandler((char*)"IN_KEY_WORD", yytext);
    return IN;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 378 "lexer.l"
{
    printf("ERROR: !IN Unsupported in this  version.\n");
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"!IN_KEY_WORD", yytext);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 384 "lexer.l"
{
    printf("ERROR: interface Unsupported in this  version.\n");
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"INTERFACE_KEY_WORD", yytext);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 390 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"INTERNAL_KEY_WORD", yytext);
    head.isInternal = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 396 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"IS_KEY_WORD", yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 401 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"!IS_KEY_WORD", yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 406 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"NULL_KEY_WORD", yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 411 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"OBJECT_KEY_WORD", yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 416 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"FINAL_KEY_WORD", yytext);
    head.isFinal = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 422 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"OVERRIDE_KEY_WORD", yytext);
    head.isOverride = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 428 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"OPEN_KEY_WORD", yytext);
    head.isOpen = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 434 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"PRIVATE_KEY_WORD", yytext);
    head.isPrivate = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 440 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"PROTECTED_KEY_WORD", yytext);
    head.isProtected = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 446 "lexer.l"
{
    multilineBegin = line;
    printHandler((char*)"PUBLIC_KEY_WORD", yytext);
    head.isPublic = 1;
    yy_push_state(MODIFIER);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 452 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"PACKAGE_KEY_WORD", yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 457 "lexer.l"
{
    printHandler((char*)"RETURN_KEY_WORD", yytext);
    return RETURN;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 461 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"SUPER_KEY_WORD", yytext);
    return SUPER;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 468 "lexer.l"
{
    
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"THIS_KEY_WORD", yytext);
    return THIS;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 476 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"THROW_KEY_WORD", yytext);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 481 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"TRY_KEY_WORD", yytext);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 486 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"TYPEALIAS_KEY_WORD", yytext);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 491 "lexer.l"
{
    printHandler((char*)"VAL_KEY_WORD", yytext);
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    return VAL;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 497 "lexer.l"
{
    printHandler((char*)"VAR_KEY_WORD", yytext);
    struct ModifierHead * copy = copyModifierHead(&head);
    yylval.modHead = copy;
    return VAR;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 503 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"WHEN_KEY_WORD", yytext);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 508 "lexer.l"
{
    printHandler((char*)"WHILE_KEY_WORD", yytext);
    return WHILE;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 513 "lexer.l"
{
    printHandler((char*)"TRUE_KEY_WORD", yytext);
    return TRUE_LITERAL;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 517 "lexer.l"
{
    printHandler((char*)"FALSE_KEY_WORD", yytext);
    return FALSE_LITERAL;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 522 "lexer.l"
{bufferString[0] = 0; multilineBegin = line; yy_push_state(MULTILINE_COMMENT);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 523 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 524 "lexer.l"
{line += 1; strcat(bufferString, yytext);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 525 "lexer.l"
{line += 1; strcat(bufferString, yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 526 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 527 "lexer.l"
{printHandler((char*)"MULTILINE_COMMENT", bufferString); yy_pop_state();}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 528 "lexer.l"
{printf("ERROR: no closing */ in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 530 "lexer.l"
{bufferString[0] = 0; yy_push_state(END_OF_LINE_COMMENT);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 531 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 532 "lexer.l"
{printHandler((char*)"END_OF_LINE_COMMENT", bufferString);  line += 1; yy_pop_state();
return ENDL; }
	YY_BREAK
case YY_STATE_EOF(END_OF_LINE_COMMENT):
#line 534 "lexer.l"
{printHandler((char*)"END_OF_LINE_COMMENT", bufferString); BEGIN(INITIAL);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 536 "lexer.l"
{
    printHandler((char*)"PLUS_OPERATOR", yytext);
    return '+';
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 540 "lexer.l"
{
    printHandler((char*)"MINUS_OPERATOR", yytext);
    return '-';
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 544 "lexer.l"
{
    printHandler((char*)"MUL_OPERATOR", yytext);
    return '*';
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 548 "lexer.l"
{
    printHandler((char*)"DIV_OPERATOR", yytext);
    return '/';
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 552 "lexer.l"
{
    printHandler((char*)"ASSIGNMENT_OPERATOR", yytext);
    yy_pop_state();
    return '=';
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 557 "lexer.l"
{
    printHandler((char*)"ASSIGNMENT_OPERATOR", yytext);
    return '=';
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 561 "lexer.l"
{
    printHandler((char*)"GREATER_EQUAL_OPERATOR", yytext);
    return GREATER_EQUAL;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 565 "lexer.l"
{
    printHandler((char*)"LESS_EQUAL_OPERATOR", yytext);
    return LESS_EQUAL;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 569 "lexer.l"
{
    printHandler((char*)"GREATER_OPERATOR", yytext);
    return '>';
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 573 "lexer.l"
{
    printHandler((char*)"LESS_OPERATOR", yytext);
    return '<';
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 577 "lexer.l"
{
    printHandler((char*)"NOT_EQUAL_OPERATOR", yytext);
    return NOT_EQUAL;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 581 "lexer.l"
{
    printHandler((char*)"EQUAL_OPERATOR", yytext);
    return EQUAL;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 585 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"MOD_OPERATOR", yytext);
    return '%';
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 592 "lexer.l"
{
    
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"DIV_ASSIGNMENT_OPERATOR", yytext);
    return DIV_ASSIGNMENT;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 600 "lexer.l"
{
    
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"PLUS_ASSIGNMENT_OPERATOR", yytext);
    return PLUS_ASSIGNMENT;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 608 "lexer.l"
{
    
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"MUL_ASSIGNMENT_OPERATOR", yytext);
    return MUL_ASSIGNMENT;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 616 "lexer.l"
{
    
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"MINUS_ASSIGNMENT_OPERATOR", yytext);
    return MINUS_ASSIGNMENT;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 624 "lexer.l"
{
    
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"MOD_ASSIGNMENT_OPERATOR", yytext);
    return MOD_ASSIGNMENT;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 633 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    return '{';
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 637 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    yy_push_state(FUNC_BODY);
    return '{';
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 642 "lexer.l"
{
    printHandler((char*)"RIGHT_BRACE", yytext);
    hasClosingBrace = 1;
    return ';';
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 647 "lexer.l"
{
    printHandler((char*)"LEFT_SQUARE_BRACKET", yytext);
    return '[';
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 651 "lexer.l"
{
    printHandler((char*)"RIGHT_SQUARE_BRACKET", yytext);
    return ']';
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 655 "lexer.l"
{
    printHandler((char*)"LEFT_ROUND_BRACKET", yytext);
    yy_push_state(INBRACKET);
    return '(';
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 660 "lexer.l"
{
    printHandler((char*)"RIGHT_ROUND_BRACKET", yytext);
    yy_pop_state();
    return ')';
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 665 "lexer.l"
{
    printHandler((char*)"COLON", yytext);
    return ':';
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 669 "lexer.l"
{
    printHandler((char*)"SEMICOLON", yytext);
    return ';';
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 673 "lexer.l"
{
    printHandler((char*)"DOT", yytext);
    return '.';
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 677 "lexer.l"
{
    printHandler((char*)"COMMA", yytext);
    return ',';
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 682 "lexer.l"
{
    
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"INCREMENT_OPERATOR", yytext);
    return INCREMENT;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 690 "lexer.l"
{
    
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"DECREMENT_OPERATOR", yytext);
    return DECREMENT;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 699 "lexer.l"
{
    
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"REF_EQUAL_OPERATOR", yytext);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 705 "lexer.l"
{
    
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"REF_NOT_EQUAL_OPERATOR", yytext);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 712 "lexer.l"
{
    printHandler((char*)"NOT_OPERATOR", yytext);
    return '!';
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 716 "lexer.l"
{
    printHandler((char*)"OR_OPERATOR", yytext);
    return DISJ;
} 
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 720 "lexer.l"
{
    printHandler((char*)"AND_OPERATOR", yytext);
    return CONJ;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 725 "lexer.l"
{
    printHandler((char*)"RANGE_OPERATOR", yytext);
    return RANGE;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 729 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"NOT_NULL_ASSERTION_OPERATOR", yytext);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 734 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"SAFE_CALL_OPERATOR", yytext);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 740 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"ELVIS_OPERATOR", yytext);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 745 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"UNIT_REFERENCE_OPERATOR", yytext);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 750 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"ALLOW_NULL_OPERATOR", yytext);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 755 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"LAMBDA_OPERATOR", yytext);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 760 "lexer.l"
{
    printf("ERROR: Unsupported in this  version : %s.\n", yytext);
    BEGIN(INITIAL);
    return -1;
    printHandler((char*)"ANNOTATION_OPERATOR", yytext);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 766 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    yy_push_state(INBRACE);
    return '{';
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 772 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    yy_push_state(INBRACE);
    return '{';
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 778 "lexer.l"
{
    printHandler((char*)"RIGHT_BRACE", yytext);
    hasClosingBrace = 1;
    yy_pop_state();
    return ';';
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 785 "lexer.l"
{
    printHandler((char*)"LEFT_BRACE", yytext);
    yy_push_state(INBRACE);
    return '{';
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 791 "lexer.l"
{
    printHandler((char*)"END_INTERPOLATION", yytext);
    bufferString[0] = 0;
    clearStringBuffer(&buff);
    hasPlus = 1;
    yy_pop_state();
    return ')';
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 800 "lexer.l"
{
    printHandler((char*)"RIGHT_BRACE", yytext);
    hasClosingBrace = 1;
    yy_pop_state();
    if (YYSTATE == FUNCTION)
    {
        yy_pop_state();
    }
    return ';';
}
	YY_BREAK
case YY_STATE_EOF(INBRACE):
#line 811 "lexer.l"
{
    printf("ERROR: expecting \"}\".\n");
    BEGIN(INITIAL);
    return -1;
}
	YY_BREAK
case YY_STATE_EOF(INTERPOLATION):
#line 817 "lexer.l"
{
    printf("ERROR: expecting \"}\".\n");
    BEGIN(INITIAL);
    return -1;
}
	YY_BREAK
case YY_STATE_EOF(FUNC_BODY):
#line 823 "lexer.l"
{
    printf("ERROR: expecting \"}\".\n");
    BEGIN(INITIAL);
    return -1;
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 829 "lexer.l"
{
    printHandler((char*)"IDENTIFIER", yytext);
    char * t = (char*)malloc(strlen(yytext) + 1);
    strcpy(t, yytext);
    yylval.ident = t;
    return ID;
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 837 "lexer.l"
{ bufferString[0] = 0;
    strcat(bufferString, yytext);
    int buffLen = strlen(bufferString);
    if (bufferString[0] == '0' && buffLen > 1)
    {
        printf("ERROR: illegal using of zero in INT in line %d.\n", line);
        return -1;
    }
    else 
    {
        removeUnderline(bufferString);
        int res = atoi(bufferString);
        if(needsTokens) printf("(%d) - DECIMAL_INT\n", res);
        yylval.intLit = res;
        return INT_LITERAL;
    }
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 855 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 860 "lexer.l"
{ 
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    removeUnderline(bufferString);
    int result = strtol(bufferString + 2, NULL, 16);
    if(needsTokens) printf("(%d) - HEX_INT\n", result);
    yylval.intLit = result;
    return INT_LITERAL;
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 870 "lexer.l"
{
    printf("ERROR: missing hex int value in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 875 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 880 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 885 "lexer.l"
{
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    removeUnderline(bufferString);
    int result = strtol(bufferString + 2, NULL, 2);
    if(needsTokens) printf("(%d) - BINARY_INT\n", result);
    yylval.intLit = result;
    return INT_LITERAL;
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 895 "lexer.l"
{
    printf("ERROR: missing binary int value in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 900 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 905 "lexer.l"
{
    printf("ERROR: illegal underscore in INT in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 910 "lexer.l"
{
    printf("ERROR: oot of range binary value in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 915 "lexer.l"
{
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    removeUnderline(bufferString);
    int resLen = strlen(bufferString);
    double result = atof(bufferString);
    if(needsTokens) printf("(%.*f) - DOUBLE\n", resLen, result);
    yylval.doubleLit = result;
    return DOUBLE_LITERAL;
}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 926 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 931 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 936 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 941 "lexer.l"
{
    printf("ERROR: illegal underscore in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 946 "lexer.l"
{
    printf("ERROR: the value is out of range in DOUBLE in line %d.\n", line);
    return -1;
}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 951 "lexer.l"
{
    bufferString[0] = 0;
    multilineBegin = line;
    printHandler((char*)"MULTILINE_STRING_BEGIN", yytext);
    yy_push_state(MULTILINE_STRING); 
}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 957 "lexer.l"
{line += 1; strcat(bufferString, yytext);}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 958 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 959 "lexer.l"
{
    printHandler((char*)"MULTILINE_STRING", bufferString);
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    strcpy(ns->buffer, bufferString);
    ns->length = strlen(bufferString);
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;
    printHandler((char*)"BEGIN_INTERPOLATION", yytext);
    bufferString[0] = 0;
    yy_push_state(INTERPOLATION);
    return STRING_LITERAL;
}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 972 "lexer.l"
{
    printHandler((char*)"MULTILINE_STRING", bufferString);
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    strcpy(ns->buffer, bufferString);
    ns->length = strlen(bufferString);
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;
    strcpy(tempIdent, yytext + 1);
    hasCloseBracket = 1;
    printHandler((char*)"BEGIN_INTERPOLATION", (char*)"$");
    printHandler((char*)"IDENTIFIER", yytext + 1);
    printHandler((char*)"END_INTERPOLATION", (char*)" ");
    bufferString[0] = 0;
    return STRING_LITERAL;
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 988 "lexer.l"
{strcat(bufferString, yytext);}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 989 "lexer.l"
{
    for (int i = 0; i < yyleng - 3; i++)
    {
        strcat(bufferString, "\"");        
    }
    printHandler((char*)"MULTILINE STRING", bufferString);
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    strcpy(ns->buffer, bufferString);
    ns->length = strlen(bufferString);
    yylval.stringLit = ns;
    printHandler((char*)"MULTILINE_STRING_END", (char*)"\"\"\"");
    yy_pop_state();
    return STRING_LITERAL;
}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_STRING):
#line 1003 "lexer.l"
{printf("ERROR: no closing \"\"\" (three double-quotes) in MULTILINE STRING in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 1005 "lexer.l"
{
    bufferString[0] = 0;
    multilineBegin = line;
    clearStringBuffer(&buff);
    printHandler((char*)"ESCAPED_STRING_BEGIN", yytext);
    yy_push_state(STRING);
}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 1012 "lexer.l"
{
    printHandler((char*)"ESCAPED_STRING", getSafeCString(&buff));

    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    memcpy(ns->buffer, buff.buffer, buff.length);
    ns->length = buff.length;
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;

    printHandler((char*)"BEGIN_INTERPOLATION", yytext);
    clearStringBuffer(&buff);
    yy_push_state(INTERPOLATION);
    return STRING_LITERAL;
}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 1027 "lexer.l"
{appendChar(&buff, yytext[0]);}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 1028 "lexer.l"
{
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    memcpy(ns->buffer, buff.buffer, buff.length);
    ns->length = buff.length;
    yylval.stringLit = ns;
    hasPlus = 1;
    hasOpenBracket = 1;
    strcpy(tempIdent, yytext + 1);
    hasCloseBracket = 1;
    printHandler((char*)"ESCAPED_STRING", getSafeCString(&buff));
    printHandler((char*)"BEGIN_INTERPOLATION", (char*)"$");
    printHandler((char*)"IDENTIFIER", yytext + 1);
    printHandler((char*)"END_INTERPOLATION", (char*)" ");
    clearStringBuffer(&buff);
    bufferString[0] = 0;
    return STRING_LITERAL;
}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 1045 "lexer.l"
{appendChars(&buff, yytext);}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 1046 "lexer.l"
{printf("ERROR: no closing \" (double-quote) in STRING in line %d.\n", multilineBegin); line += 1; yy_pop_state(); return -1;}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 1047 "lexer.l"
{ 
    printHandler((char*)"ESCAPED STRING", getSafeCString(&buff)); 
    printHandler((char*)"ESCAPED_STRING_END", yytext);
    yy_pop_state();
    struct stringBuffer * ns = (struct stringBuffer*)malloc(sizeof(struct stringBuffer));
    memcpy(ns->buffer, buff.buffer, buff.length);
    ns->length = buff.length;
    yylval.stringLit = ns;
    return STRING_LITERAL;
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 1057 "lexer.l"
{printf("ERROR: no closing \" (double-quote) in STRING in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 1059 "lexer.l"
{bufferString[0] = 0; multilineBegin = line; clearStringBuffer(&buff); yy_push_state(CHAR);}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 1060 "lexer.l"
{appendChar(&buff, yytext[0]);}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 1061 "lexer.l"
{printf("ERROR: no closing  \' (single-quote) in CHAR in line %d.\n", multilineBegin); line += 1; yy_pop_state(); return -1;}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 1062 "lexer.l"
{
    int buffLen = buff.length;
    int isOk = 0;
    if(buffLen > 1)
    {
        printf("ERROR: Too many characters in a character literal in line %d.\n", multilineBegin);
    }
    else if (buffLen <= 0)
    {
        printf("ERROR: empty character literal in line %d.\n", multilineBegin);
    }
    else
    {
        if (needsTokens) printf("(%c) - CHAR\n", buff.buffer[0]);
        isOk = 1;
    }
    yy_pop_state();
    if(isOk) 
    {        
        yylval.charLit = buff.buffer[0];
        return CHAR_LITERAL;
    }
    else
    {
        return -1;
    }
}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 1089 "lexer.l"
{printf("ERROR: no closing \' (single-quote) in CHAR in line %d.\n", multilineBegin); BEGIN(INITIAL); return -1;}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 1091 "lexer.l"
{appendChar(&buff, '\n');}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 1092 "lexer.l"
{appendChar(&buff, '\t');}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 1093 "lexer.l"
{appendChar(&buff, '\b');}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 1094 "lexer.l"
{appendChar(&buff, '\r');}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 1095 "lexer.l"
{appendChar(&buff, '$');}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 1096 "lexer.l"
{appendChar(&buff, '\"');}
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 1097 "lexer.l"
{appendChar(&buff, '\'');}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 1098 "lexer.l"
{appendChar(&buff, '\\');}
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 1099 "lexer.l"
{
    if (strlen(yytext) < 4)
    {
        printf("ERROR: Illegal escape \'\\u\' in line %d\n", line);
        return -1;
    }
    int value = strtol(yytext+2,NULL, 16);
    if (value > 127)
    {
        printf("ERROR: non-supported UNICODE character in line %d.\n", line);
        return -1;
    }
    else
    {
        appendChar(&buff, value);
    }
}
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 1117 "lexer.l"
{
    // Игнорирование лишних пробелов и табуляций. 
}
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 1121 "lexer.l"
{
    line = line + 1;
}
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 1125 "lexer.l"
{
    line = line + 1;
}
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 1129 "lexer.l"
{
    line = line + 1;
    return ENDL;
}
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 1134 "lexer.l"
{
    bufferString[0] = 0;
    strcat(bufferString, yytext);
    printf("%s - UNRECOGNIZED TOKEN.\n", bufferString);
    return -1;
}
	YY_BREAK
case YY_STATE_EOF(MODIFIER):
#line 1141 "lexer.l"
{
    BEGIN(OVER);
    printf("ERROR: Exprecting top level declaration in line %d.\n", multilineBegin);
    return -1;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 1147 "lexer.l"
{ 
    BEGIN(OVER);
    return ';';
}
	YY_BREAK
case YY_STATE_EOF(OVER):
#line 1152 "lexer.l"
{
    yyterminate();
}
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 1156 "lexer.l"
ECHO;
	YY_BREAK
#line 2758 "lex.yy.c"
case YY_STATE_EOF(INBRACKET):
case YY_STATE_EOF(FUNCTION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 456 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 456 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 455);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 1156 "lexer.l"


int removeCharFromStringByIndex(char * str, int index) 
{
    int length = strlen(str); // Вычислить длину строки.
    if (index >= length || index < 0) // Удалить символ, если индекс выходит за границу строки. 
    {
        return 1;
    }
    for (int i = index; i < length; i++)
    str[i] = str[i + 1];

    return 0;
}

void removeUnderline(char* str)
{
    char* underline = strchr(str, '_');
    while (underline != NULL){
        underline = strchr(str, '_');
        int position = underline - str;
        removeCharFromStringByIndex(str, position);
    }
}

void printHandler(char* str, char * token)
{
    if(needsTokens != 0)
    {
        printf("(%s) - %s\n", token, str);
    }
}
